"""
Additional scenarios: Data Exfiltration (DE-01, DE-03, DE-04) and Brute Force (BF-02, BF-03, BF-04).

These cover insider threats, DNS tunneling, legitimate email DLP triggers,
internal password sprays, forgotten passwords, and monitoring service auth failures.
"""

EXFIL_BRUTE_SCENARIOS = [
    # -----------------------------------------------------------------
    # DE-01: USB Mass Copy by Departing Employee -- True Positive, Medium
    # -----------------------------------------------------------------
    {
        "id": "DE-01",
        "difficulty": "medium",
        "alert": {
            "ticket_id": "INC-2024-00231",
            "timestamp": "2024-01-22T17:42:00Z",
            "source_tool": "Symantec DLP",
            "alert_type": "data_exfiltration",
            "severity_reported": "high",
            "summary": "DLP policy violation: 847 files (23.4 GB) copied to removable USB storage device (SanDisk Ultra 128GB, first connected today). Files include CAD drawings, Python ML model source code, customer lists, and contract PDFs. User rahul.deshpande@acmecorp.com submitted resignation 7 days ago.",
            "affected_user": "rahul.deshpande@acmecorp.com",
            "affected_device": "LAPTOP-RD-4410",
            "source_ip": "10.0.14.77",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Rahul Deshpande",
                "department": "R&D",
                "role": "Senior ML Engineer",
                "hire_date": "2019-08-12",
                "risk_score": "high",
                "manager": "sunita.rao@acmecorp.com",
                "access_level": "elevated",
                "mfa_enabled": True,
                "recent_security_training": "2023-09-15",
                "notes": "Submitted resignation on 2024-01-15. Last working day: 2024-02-15. HR exit interview scheduled 2024-02-10. Has access to proprietary ML pipeline and R&D file shares.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-22T08:55:00Z", "ip": "10.0.14.77", "location": "Office-Floor4-R&D", "device": "LAPTOP-RD-4410", "status": "success", "mfa": "passed"},
                    {"timestamp": "2024-01-21T09:02:00Z", "ip": "10.0.14.77", "location": "Office-Floor4-R&D", "device": "LAPTOP-RD-4410", "status": "success", "mfa": "passed"},
                    {"timestamp": "2024-01-20T09:10:00Z", "ip": "10.0.14.77", "location": "Office-Floor4-R&D", "device": "LAPTOP-RD-4410", "status": "success", "mfa": "passed"},
                ],
                "summary": "Normal daily login pattern from office. No remote access. Consistent device and location.",
            },
            "ip_reputation": {
                "ip": "10.0.14.77",
                "abuse_score": 0,
                "country": "Internal",
                "isp": "AcmeCorp Internal Network",
                "threat_tags": [],
                "note": "Internal corporate IP — R&D VLAN.",
            },
            "device_info": {
                "device_id": "LAPTOP-RD-4410",
                "type": "laptop",
                "os": "Windows 11 Pro 23H2",
                "last_patch": "2024-01-18",
                "encryption": "BitLocker enabled",
                "edr_status": "CrowdStrike active — no malware detected",
                "registered_owner": "rahul.deshpande@acmecorp.com",
                "last_scan": "2024-01-22T06:00:00Z",
                "usb_events": [
                    {"timestamp": "2024-01-22T17:28:00Z", "device_name": "SanDisk Ultra USB 3.0 128GB", "serial": "4C530001220914116015", "action": "first_connected"},
                ],
                "notes": "USB device has never been connected to any AcmeCorp device before today.",
            },
            "email_headers": None,
            "file_analysis": {
                "copy_tool": "robocopy.exe",
                "copy_command": "robocopy E:\\Projects F:\\ /S /E /MT:16",
                "total_files": 847,
                "total_size": "23.4 GB",
                "file_breakdown": [
                    {"type": ".py", "count": 312, "size": "1.8 GB", "description": "Python source — ML models and training pipelines"},
                    {"type": ".dwg", "count": 89, "size": "4.2 GB", "description": "AutoCAD drawings — proprietary hardware designs"},
                    {"type": ".pdf", "count": 156, "size": "890 MB", "description": "Contracts, NDAs, vendor agreements"},
                    {"type": ".xlsx", "count": 43, "size": "340 MB", "description": "Customer lists, pricing sheets, revenue data"},
                    {"type": ".pth", "count": 18, "size": "14.1 GB", "description": "PyTorch model checkpoints — trained proprietary models"},
                    {"type": "other", "count": 229, "size": "2.07 GB", "description": "Config files, datasets, documentation"},
                ],
                "classification_labels_matched": ["Confidential", "Internal Only", "Trade Secret"],
                "dlp_policy_triggered": "USB-BLOCK-SENSITIVE — copy of classified files to removable media",
            },
            "network_logs": {
                "connections": [
                    {"timestamp": "2024-01-22T16:50:00Z", "dest_ip": "10.0.14.10", "dest_port": 445, "protocol": "SMB", "bytes_received": 23400000000, "duration": "38m", "service": "R&D File Share (\\\\rd-nas-01\\projects)"},
                ],
                "summary": "User accessed R&D file share and downloaded 23.4 GB over SMB before copying to USB. Bulk download from network share is unusual for this user — average daily transfer is 200 MB.",
            },
            "threat_intel": {
                "campaign": None,
                "mitre_attack": ["T1052.001 (Exfiltration Over Physical Medium: USB)", "T1039 (Data from Network Shared Drive)", "T1074.001 (Data Staged: Local Data Staging)"],
                "related_iocs": [],
                "confidence": "high",
                "advisory": "Insider threat pattern: departing employee copying proprietary data to personal USB device. Matches Waymo/Levandowski and similar trade-secret theft cases.",
            },
        },
        "ground_truth": {
            "classification": "true_positive",
            "severity": "critical",
            "actions": ["disable_user_account", "isolate_device", "send_employee_alert", "notify_manager", "escalate_to_tier2"],
            "explanation": "Departing employee (resigned 7 days ago) copying 847 files (23.4 GB) of proprietary data — ML models, CAD drawings, customer lists, contracts — to a brand-new USB drive using robocopy. This is a textbook insider threat. The USB was first connected today, bulk SMB download is 100x his daily average, and files carry Confidential/Trade Secret labels. Disable account immediately, isolate device to preserve forensic evidence, notify manager and legal, and escalate.",
        },
        "relevant_investigations": ["user_profile", "file_analysis", "device_info", "network_logs", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # DE-03: DNS Tunneling Exfiltration -- True Positive, Hard
    # -----------------------------------------------------------------
    {
        "id": "DE-03",
        "difficulty": "hard",
        "alert": {
            "ticket_id": "INC-2024-00248",
            "timestamp": "2024-01-23T02:17:00Z",
            "source_tool": "Palo Alto DNS Security",
            "alert_type": "data_exfiltration",
            "severity_reported": "medium",
            "summary": "Anomalous DNS activity detected: workstation DESKTOP-KV-0803 generated 4,247 DNS queries in the past hour to domain cdn-analytics.net. High percentage of unique subdomains with unusual entropy. TXT query ratio is 62% vs. organizational baseline of 0.3%.",
            "affected_user": "kavita.verma@acmecorp.com",
            "affected_device": "DESKTOP-KV-0803",
            "source_ip": "10.0.22.115",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Kavita Verma",
                "department": "Finance",
                "role": "Financial Analyst",
                "hire_date": "2022-03-14",
                "risk_score": "low",
                "manager": "vikram.mehta@acmecorp.com",
                "access_level": "standard",
                "mfa_enabled": True,
                "recent_security_training": "2023-11-01",
                "notes": "No HR flags. User is likely unaware of compromise — no insider threat indicators.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-22T09:05:00Z", "ip": "10.0.22.115", "location": "Office-Floor2", "device": "DESKTOP-KV-0803", "status": "success", "mfa": "passed"},
                    {"timestamp": "2024-01-21T09:12:00Z", "ip": "10.0.22.115", "location": "Office-Floor2", "device": "DESKTOP-KV-0803", "status": "success", "mfa": "passed"},
                ],
                "summary": "Normal office login pattern. No unusual login activity.",
            },
            "ip_reputation": {
                "ip": "185.156.73.44",
                "abuse_score": 88,
                "country": "MD",
                "isp": "Stark Industries Solutions Ltd",
                "asn": "AS44477",
                "threat_tags": ["c2-server", "bulletproof-hosting", "apt-infrastructure", "dns-tunneling"],
                "last_reported": "2024-01-20",
                "virustotal_detections": "11/87 engines flagged as malicious",
                "first_seen": "2023-11-05",
                "note": "Stark Industries (Moldova) is a known bulletproof hosting provider frequently used by APT groups. AS44477 has hosted OilRig/APT34 infrastructure.",
            },
            "device_info": {
                "device_id": "DESKTOP-KV-0803",
                "type": "desktop",
                "os": "Windows 11 Pro 23H2",
                "last_patch": "2024-01-15",
                "encryption": "BitLocker enabled",
                "edr_status": "CrowdStrike active — no detections (DNS tunneling evaded behavioral engine)",
                "registered_owner": "kavita.verma@acmecorp.com",
                "last_scan": "2024-01-23T06:00:00Z",
                "suspicious_processes": [
                    {
                        "name": "svchost32.exe",
                        "path": "C:\\Users\\kavita.verma\\AppData\\Local\\Temp\\svchost32.exe",
                        "pid": 7284,
                        "parent": "explorer.exe",
                        "started": "2024-01-22T10:14:00Z",
                        "hash_sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                        "signed": False,
                        "note": "Masquerades as svchost.exe but (1) wrong name — real process is svchost.exe, not svchost32.exe; (2) wrong path — real svchost runs from System32; (3) parent is explorer.exe instead of services.exe.",
                    },
                ],
            },
            "email_headers": None,
            "file_analysis": {
                "filename": "svchost32.exe",
                "hash_sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                "file_size": "2.1 MB",
                "signed": False,
                "virustotal_detections": "6/72 engines detected (low detection due to custom packing)",
                "detection_names": ["Trojan.DNSTunnel.Gen", "Backdoor.Win32.DNScat", "HackTool.DNSExfil"],
                "behavioral_analysis": {
                    "dns_queries_per_hour": 4247,
                    "unique_subdomain_ratio": "99.86%",
                    "average_subdomain_entropy": "5.1 bits/char",
                    "txt_query_ratio": "62% (org baseline: 0.3%)",
                    "estimated_exfil_rate": "~48 MB/hour",
                    "target_domain": "cdn-analytics.net",
                    "sample_queries": [
                        "dG8gYmUgb3Igbm90IHRv.cdn-analytics.net",
                        "aXMgdGhhdCBpcyB0aGUg.cdn-analytics.net",
                        "cXVlc3Rpb24gd2hldGhl.cdn-analytics.net",
                    ],
                    "encoding": "Base64 in subdomain labels",
                },
                "iocs": ["185.156.73.44", "cdn-analytics.net", "svchost32.exe"],
            },
            "network_logs": {
                "dns_queries": [
                    {"timestamp": "2024-01-23T02:15:00Z", "domain": "dG8gYmUgb3Igbm90IHRv.cdn-analytics.net", "query_type": "TXT", "resolved_ip": "185.156.73.44", "response_size": 512},
                    {"timestamp": "2024-01-23T02:15:01Z", "domain": "aXMgdGhhdCBpcyB0aGUg.cdn-analytics.net", "query_type": "TXT", "resolved_ip": "185.156.73.44", "response_size": 512},
                    {"timestamp": "2024-01-23T02:15:02Z", "domain": "cXVlc3Rpb24gd2hldGhl.cdn-analytics.net", "query_type": "TXT", "resolved_ip": "185.156.73.44", "response_size": 512},
                ],
                "connections": [
                    {"timestamp": "2024-01-23T01:17:00Z", "dest_ip": "185.156.73.44", "dest_port": 53, "protocol": "DNS/UDP", "queries_count": 4247, "duration": "60m", "bytes_sent": 2120000, "bytes_received": 2170000},
                ],
                "summary": "4,247 DNS queries/hour to single domain cdn-analytics.net. 99.86% unique subdomains with base64-encoded payloads. 62% TXT queries (normal is 0.3%). Estimated data exfiltration rate: ~48 MB/hour. All queries resolve to 185.156.73.44 (bulletproof hosting, Moldova).",
                "domain_whois": {
                    "domain": "cdn-analytics.net",
                    "registered": "2024-01-01",
                    "registrar": "NameSilo LLC",
                    "registrant": "WhoisGuard Protected",
                    "nameservers": ["ns1.stark-dns.net", "ns2.stark-dns.net"],
                    "note": "Domain registered 23 days ago. No legitimate web presence. Nameservers on same bulletproof hosting provider.",
                },
            },
            "threat_intel": {
                "campaign": "DNS tunneling exfiltration — tooling consistent with DNScat2 or custom OilRig/APT34 DNS tunnel implant",
                "mitre_attack": ["T1048.003 (Exfiltration Over Alternative Protocol: DNS)", "T1071.004 (Application Layer Protocol: DNS)", "T1132.001 (Data Encoding: Standard Encoding)"],
                "related_iocs": ["185.156.73.44", "cdn-analytics.net", "svchost32.exe", "AS44477"],
                "threat_actor": "APT34/OilRig (medium confidence)",
                "confidence": "high",
                "advisory": "DNS tunneling is an advanced exfiltration technique that bypasses most network security controls. The combination of base64-encoded subdomains, abnormal TXT query ratio, near-100% unique subdomains, high entropy, and bulletproof hosting destination is a definitive indicator of data exfiltration over DNS.",
            },
        },
        "ground_truth": {
            "classification": "true_positive",
            "severity": "critical",
            "actions": ["isolate_device", "block_ip", "send_employee_alert", "escalate_to_tier2"],
            "explanation": "Active DNS tunneling exfiltration. A malicious process (svchost32.exe — note the fake name, wrong path, wrong parent process) is exfiltrating data via 4,247 DNS queries/hour to cdn-analytics.net, a 23-day-old domain on bulletproof hosting in Moldova. Subdomains are base64-encoded data, 62% TXT queries (vs 0.3% baseline), 99.86% unique subdomains, 5.1 bits/char entropy. Estimated exfil rate is ~48 MB/hour. The user (Finance Analyst) is likely a compromised victim, not an insider threat. Isolate immediately, block the C2 domain/IP, alert user, and escalate for full forensic investigation and org-wide threat hunt.",
        },
        "relevant_investigations": ["device_info", "file_analysis", "network_logs", "ip_reputation", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # DE-04: Large Email Attachments to Approved Partner -- False Positive, Medium
    # -----------------------------------------------------------------
    {
        "id": "DE-04",
        "difficulty": "medium",
        "alert": {
            "ticket_id": "INC-2024-00259",
            "timestamp": "2024-01-24T10:18:00Z",
            "source_tool": "Zscaler DLP",
            "alert_type": "data_exfiltration",
            "severity_reported": "high",
            "summary": "DLP alert: User ananya.iyer@acmecorp.com sent email with 51 MB of attachments (Q1 QBR package) to external recipient deepak.shah@partnertech.com. Content scan flagged keywords: 'Revenue' (142 matches), 'Margin' (38 matches), 'Confidential' (84 matches), and multiple dollar amounts exceeding $1M.",
            "affected_user": "ananya.iyer@acmecorp.com",
            "affected_device": "LAPTOP-AI-2207",
            "source_ip": "10.0.10.44",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Ananya Iyer",
                "department": "Sales",
                "role": "Sales Director — Enterprise Accounts",
                "hire_date": "2018-04-02",
                "risk_score": "low",
                "manager": "rohan.gupta@acmecorp.com",
                "access_level": "elevated",
                "mfa_enabled": True,
                "recent_security_training": "2023-12-10",
                "notes": "Senior sales leader. Responsible for PartnerTech relationship since 2019. Regularly sends QBR materials to partner contacts. No HR flags.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-24T08:50:00Z", "ip": "10.0.10.44", "location": "Office-Floor1-Sales", "device": "LAPTOP-AI-2207", "status": "success", "mfa": "passed"},
                    {"timestamp": "2024-01-23T09:05:00Z", "ip": "10.0.10.44", "location": "Office-Floor1-Sales", "device": "LAPTOP-AI-2207", "status": "success", "mfa": "passed"},
                ],
                "summary": "Normal daily login pattern from office. No anomalies.",
            },
            "ip_reputation": {
                "ip": "10.0.10.44",
                "abuse_score": 0,
                "country": "Internal",
                "isp": "AcmeCorp Internal Network",
                "threat_tags": [],
                "note": "Internal corporate IP — Sales VLAN.",
            },
            "device_info": {
                "device_id": "LAPTOP-AI-2207",
                "type": "laptop",
                "os": "Windows 11 Pro 23H2",
                "last_patch": "2024-01-20",
                "encryption": "BitLocker enabled",
                "edr_status": "CrowdStrike active — no threats",
                "registered_owner": "ananya.iyer@acmecorp.com",
                "last_scan": "2024-01-24T06:00:00Z",
            },
            "email_headers": {
                "from": "ananya.iyer@acmecorp.com",
                "to": "deepak.shah@partnertech.com",
                "cc": "rohan.gupta@acmecorp.com",
                "subject": "Q1 2024 QBR Package — AcmeCorp x PartnerTech",
                "spf": "pass",
                "dkim": "pass",
                "dmarc": "pass",
                "attachments": [
                    {"filename": "AcmeCorp_PartnerTech_QBR_Q1_2024.pptx", "size": "47.2 MB", "note": "PowerPoint deck with embedded charts and images"},
                    {"filename": "QBR_Revenue_Breakdown_Q1_2024.xlsx", "size": "3.8 MB", "note": "Revenue and pipeline spreadsheet"},
                ],
                "dlp_keyword_matches": {
                    "Revenue": 142,
                    "Margin": 38,
                    "Confidential": 84,
                    "dollar_amounts_over_1M": 12,
                },
                "notes": "'Confidential' matches are from the standard AcmeCorp slide template footer ('AcmeCorp Confidential') present on all 84 slides. This is boilerplate, not a sensitivity indicator.",
            },
            "file_analysis": None,
            "network_logs": {
                "connections": [
                    {"timestamp": "2024-01-24T10:18:00Z", "dest_ip": "40.107.22.100", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 53500000, "bytes_received": 2400, "duration": "90s", "service": "Microsoft 365 — Outlook (smtp.office365.com)"},
                ],
                "summary": "Email sent via corporate Microsoft 365 tenant to partnertech.com. Normal outbound email flow.",
            },
            "threat_intel": {
                "campaign": None,
                "mitre_attack": [],
                "related_iocs": [],
                "confidence": "none",
                "advisory": "No threat intelligence matches. Recipient domain partnertech.com is on the organization allow-list (added 2019-06-15). Active NDA on file (signed 2019-07-01, renewed 2023-07-01). CRM shows 47 interactions with this contact in the past 12 months.",
                "prior_dlp_history": [
                    {"date": "2023-10-18", "subject": "Q3 2023 QBR Package", "size": "44 MB", "disposition": "false_positive"},
                    {"date": "2023-07-20", "subject": "Q2 2023 QBR Package", "size": "39 MB", "disposition": "false_positive"},
                    {"date": "2023-04-15", "subject": "Q1 2023 QBR Package", "size": "41 MB", "disposition": "false_positive"},
                ],
            },
        },
        "ground_truth": {
            "classification": "false_positive",
            "severity": "low",
            "actions": [],
            "explanation": "Sales Director sending quarterly QBR package to a long-standing, allow-listed partner (PartnerTech, on allow-list since 2019, active NDA on file). The 'Confidential' keyword matches (84) are from the standard slide template footer on all slides — not an actual sensitivity marker. DLP flagged revenue/margin keywords that are expected in a business review. Manager (rohan.gupta) is CC'd. Three previous identical QBR emails were all closed as false positives. This is normal business activity.",
        },
        "relevant_investigations": ["user_profile", "email_headers", "network_logs", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # BF-02: Internal Password Spray -- True Positive, Hard
    # -----------------------------------------------------------------
    {
        "id": "BF-02",
        "difficulty": "hard",
        "alert": {
            "ticket_id": "INC-2024-00273",
            "timestamp": "2024-01-25T01:47:00Z",
            "source_tool": "Microsoft Defender for Identity",
            "alert_type": "brute_force",
            "severity_reported": "medium",
            "summary": "Multiple authentication failures detected from internal workstation 10.12.50.88. 741 failed login attempts across 247 unique accounts in 33 minutes. Source device belongs to sanjay.mane@acmecorp.com.",
            "affected_user": "sanjay.mane@acmecorp.com",
            "affected_device": "DESKTOP-SM-0612",
            "source_ip": "10.12.50.88",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Sanjay Mane",
                "department": "IT Support",
                "role": "Helpdesk Technician",
                "hire_date": "2023-02-20",
                "risk_score": "low",
                "manager": "pooja.kulkarni@acmecorp.com",
                "access_level": "standard",
                "mfa_enabled": True,
                "recent_security_training": "2023-10-01",
                "notes": "User is likely not the attacker — workstation may be compromised. User was not logged in at the time of the attack (01:47 AM). Last interactive logon was 2024-01-24 at 17:30.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-25T01:14:00Z", "source_ip": "10.12.50.88", "targets": "247 unique accounts", "total_attempts": 741, "attempts_per_account": 3, "passwords_tried": ["Spring2026!", "Acme2026!", "Welcome123!"], "duration": "33 minutes", "status": "735 failed, 6 succeeded"},
                    {"timestamp": "2024-01-25T01:47:30Z", "source_ip": "10.12.50.88", "target": "svc-backup@acmecorp.com", "status": "success", "note": "Service account — member of Domain Admins. Password age: 847 days."},
                    {"timestamp": "2024-01-25T01:48:00Z", "source_ip": "10.12.50.88", "target": "amit.patil@acmecorp.com", "status": "success", "note": "Marketing Coordinator"},
                    {"timestamp": "2024-01-25T01:49:00Z", "source_ip": "10.12.50.88", "target": "neelam.bhat@acmecorp.com", "status": "success", "note": "Accounts Payable"},
                    {"timestamp": "2024-01-25T01:50:00Z", "source_ip": "10.12.50.88", "target": "vivek.joshi@acmecorp.com", "status": "success", "note": "Sales Rep"},
                    {"timestamp": "2024-01-25T01:51:00Z", "source_ip": "10.12.50.88", "target": "prerna.nair@acmecorp.com", "status": "success", "note": "HR Associate"},
                    {"timestamp": "2024-01-25T01:52:00Z", "source_ip": "10.12.50.88", "target": "gaurav.kulkarni@acmecorp.com", "status": "success", "note": "Facilities"},
                ],
                "compromised_accounts": [
                    {"account": "svc-backup@acmecorp.com", "role": "Service Account — Domain Admins member", "password_age_days": 847, "mfa": False, "note": "CRITICAL — Domain Admin privileges. Password not rotated in 2+ years."},
                    {"account": "amit.patil@acmecorp.com", "password_age_days": 312, "mfa": True},
                    {"account": "neelam.bhat@acmecorp.com", "password_age_days": 445, "mfa": True},
                    {"account": "vivek.joshi@acmecorp.com", "password_age_days": 201, "mfa": True},
                    {"account": "prerna.nair@acmecorp.com", "password_age_days": 178, "mfa": True},
                    {"account": "gaurav.kulkarni@acmecorp.com", "password_age_days": 523, "mfa": True},
                ],
                "summary": "Password spray attack: exactly 3 attempts per account (below lockout threshold of 5) across 247 accounts in 33 minutes. 6 accounts compromised. svc-backup is a Domain Admins member with an 847-day-old password and no MFA — highest risk compromise.",
            },
            "ip_reputation": {
                "ip": "10.12.50.88",
                "abuse_score": 0,
                "country": "Internal",
                "isp": "AcmeCorp Internal Network",
                "threat_tags": [],
                "note": "Internal corporate IP — IT Support VLAN. This is the IP of DESKTOP-SM-0612, a helpdesk workstation. The device appears compromised.",
            },
            "device_info": {
                "device_id": "DESKTOP-SM-0612",
                "type": "desktop",
                "os": "Windows 11 Pro 23H2",
                "last_patch": "2024-01-18",
                "encryption": "BitLocker enabled",
                "edr_status": "CrowdStrike active — process alert: suspicious renamed binary detected",
                "registered_owner": "sanjay.mane@acmecorp.com",
                "last_scan": "2024-01-25T06:00:00Z",
                "suspicious_processes": [
                    {
                        "name": "winlogon_helper.exe",
                        "original_name": "Rubeus.exe",
                        "path": "C:\\Users\\sanjay.mane\\AppData\\Local\\Temp\\winlogon_helper.exe",
                        "pid": 4892,
                        "parent": "powershell.exe",
                        "started": "2024-01-25T01:12:00Z",
                        "hash_sha256": "7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b",
                        "signed": False,
                        "note": "Rubeus.exe — Kerberos abuse/password spray tool — renamed to evade detection.",
                    },
                ],
                "post_compromise_activity": [
                    {"timestamp": "2024-01-25T01:55:00Z", "action": "RDP connection to 10.0.1.25 (backup-srv-01) using svc-backup credentials"},
                    {"timestamp": "2024-01-25T02:10:00Z", "action": "ntdsutil.exe executed on backup-srv-01 — NTDS.dit staged at C:\\Windows\\Temp\\ntds_export\\"},
                    {"timestamp": "2024-01-25T02:25:00Z", "action": "7z.exe compressing NTDS.dit export — Active Directory database exfiltration attempt"},
                ],
            },
            "email_headers": None,
            "file_analysis": {
                "filename": "winlogon_helper.exe",
                "original_filename": "Rubeus.exe",
                "hash_sha256": "7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b",
                "file_size": "428 KB",
                "signed": False,
                "virustotal_detections": "52/72 engines detected",
                "detection_names": ["HackTool.Rubeus", "HackTool.Win32.Kerberos", "Riskware.PasswordSpray"],
                "note": "Rubeus is a legitimate red-team tool commonly abused by attackers for Kerberos ticket manipulation and password spraying.",
            },
            "network_logs": {
                "connections": [
                    {"timestamp": "2024-01-25T01:14:00Z", "src_ip": "10.12.50.88", "dest_ip": "10.0.1.10", "dest_port": 88, "protocol": "Kerberos", "connection_count": 741, "duration": "33m", "note": "Password spray against Domain Controller"},
                    {"timestamp": "2024-01-25T01:55:00Z", "src_ip": "10.12.50.88", "dest_ip": "10.0.1.25", "dest_port": 3389, "protocol": "RDP", "duration": "35m", "note": "Lateral movement to backup server using svc-backup credentials"},
                ],
                "summary": "741 Kerberos authentication attempts to DC in 33 minutes, followed by RDP lateral movement to backup server. Attacker used compromised svc-backup (Domain Admins) to access backup-srv-01 and stage NTDS.dit for exfiltration.",
            },
            "threat_intel": {
                "campaign": "Internal password spray — consistent with Nobelium/SolarWinds tradecraft. Low-and-slow approach staying below lockout thresholds.",
                "mitre_attack": ["T1110.003 (Brute Force: Password Spraying)", "T1078.002 (Valid Accounts: Domain Accounts)"],
                "related_iocs": ["winlogon_helper.exe (Rubeus)", "svc-backup compromise", "NTDS.dit staging"],
                "threat_actor": "Unknown — advanced tradecraft (stayed below lockout, targeted service accounts, immediate lateral movement)",
                "confidence": "high",
                "advisory": "Password spray stayed below lockout threshold (3 attempts vs. 5 threshold). Compromised a Domain Admin service account with an 847-day-old password. Post-compromise: lateral movement via RDP, NTDS.dit dump (full AD credential extraction). This is a critical incident — assume full domain compromise.",
            },
        },
        "ground_truth": {
            "classification": "true_positive",
            "severity": "critical",
            "actions": ["disable_user_account", "isolate_device", "reset_user_password", "send_employee_alert", "escalate_to_tier2"],
            "explanation": "Internal password spray from compromised workstation using Rubeus (renamed to evade detection). 247 accounts targeted with 3 attempts each (below lockout threshold of 5). 6 accounts compromised, including svc-backup — a Domain Admins service account with an 847-day-old password and no MFA. Post-compromise activity: attacker RDP'd to backup server and staged NTDS.dit (full AD credential database). This is a critical incident — disable all compromised accounts, isolate both the source workstation and backup server, force password resets for all 6 compromised accounts plus svc-backup, and escalate immediately. Assume full domain compromise until proven otherwise.",
        },
        "relevant_investigations": ["login_history", "device_info", "file_analysis", "network_logs", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # BF-03: Forgot Password After Vacation -- False Positive, Easy
    # -----------------------------------------------------------------
    {
        "id": "BF-03",
        "difficulty": "easy",
        "alert": {
            "ticket_id": "INC-2024-00285",
            "timestamp": "2024-01-26T09:14:00Z",
            "source_tool": "Microsoft Defender for Identity",
            "alert_type": "brute_force",
            "severity_reported": "medium",
            "summary": "Account lockout detected: 5 failed login attempts for user manisha.garcia@acmecorp.com from device LAPTOP-MGARCIA within 4 minutes. Account locked out per policy (threshold: 5 attempts).",
            "affected_user": "manisha.garcia@acmecorp.com",
            "affected_device": "LAPTOP-MGARCIA",
            "source_ip": "10.0.18.92",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Manisha Garcia",
                "department": "Customer Support",
                "role": "Support Team Lead",
                "hire_date": "2020-11-09",
                "risk_score": "low",
                "manager": "arjun.nair@acmecorp.com",
                "access_level": "standard",
                "mfa_enabled": True,
                "recent_security_training": "2023-11-20",
                "notes": "PTO approved: 2024-01-12 to 2024-01-25 (2 weeks vacation). Password expiration date was 2024-01-20 — expired during vacation. Returned to office today (2024-01-26).",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-26T09:10:00Z", "ip": "10.0.18.92", "device": "LAPTOP-MGARCIA", "status": "failed", "logon_type": "Interactive (Type 2)", "reason": "expired_password"},
                    {"timestamp": "2024-01-26T09:11:15Z", "ip": "10.0.18.92", "device": "LAPTOP-MGARCIA", "status": "failed", "logon_type": "Interactive (Type 2)", "reason": "expired_password"},
                    {"timestamp": "2024-01-26T09:12:00Z", "ip": "10.0.18.92", "device": "LAPTOP-MGARCIA", "status": "failed", "logon_type": "Interactive (Type 7)", "reason": "expired_password"},
                    {"timestamp": "2024-01-26T09:13:10Z", "ip": "10.0.18.92", "device": "LAPTOP-MGARCIA", "status": "failed", "logon_type": "Interactive (Type 7)", "reason": "expired_password"},
                    {"timestamp": "2024-01-26T09:14:00Z", "ip": "10.0.18.92", "device": "LAPTOP-MGARCIA", "status": "failed", "logon_type": "Interactive (Type 2)", "reason": "account_locked"},
                    {"timestamp": "2024-01-11T17:30:00Z", "ip": "10.0.18.92", "device": "LAPTOP-MGARCIA", "status": "success", "logon_type": "Interactive (Type 2)", "note": "Last successful login — day before vacation started"},
                ],
                "summary": "5 failed attempts in 4 minutes, all from same device (LAPTOP-MGARCIA), all Interactive logon (Type 2/7 — physical keyboard login). Intervals of 30-90 seconds between attempts (consistent with human typing speed, not automated). Password expired on Jan 20 while user was on approved 2-week vacation (Jan 12-25). User returned today.",
            },
            "ip_reputation": {
                "ip": "10.0.18.92",
                "abuse_score": 0,
                "country": "Internal",
                "isp": "AcmeCorp Internal Network",
                "threat_tags": [],
                "note": "Internal corporate IP — Customer Support VLAN.",
            },
            "device_info": {
                "device_id": "LAPTOP-MGARCIA",
                "type": "laptop",
                "os": "Windows 11 Pro 23H2",
                "last_patch": "2024-01-10",
                "encryption": "BitLocker enabled",
                "edr_status": "CrowdStrike active — no threats",
                "registered_owner": "manisha.garcia@acmecorp.com",
                "last_scan": "2024-01-26T06:00:00Z",
                "notes": "Device was powered off during user's 2-week vacation (Jan 12-25). Powered on today at 09:08.",
            },
            "email_headers": None,
            "file_analysis": None,
            "network_logs": {
                "connections": [],
                "summary": "No network activity from this device other than the authentication attempts. User could not establish a session because login never succeeded.",
            },
            "threat_intel": {
                "campaign": None,
                "mitre_attack": [],
                "related_iocs": [],
                "confidence": "none",
                "advisory": "No threat intelligence matches. Helpdesk ticket HD-2026-04-04-0847 opened by user at 09:17 (3 minutes after lockout) requesting password reset. PTO records confirm 2-week vacation spanning the password expiration date.",
                "helpdesk_ticket": {
                    "id": "HD-2026-04-04-0847",
                    "opened": "2024-01-26T09:17:00Z",
                    "requester": "manisha.garcia@acmecorp.com",
                    "category": "Password Reset",
                    "description": "Returning from vacation, password expired and account is locked. Please reset.",
                    "status": "resolved",
                    "resolved_by": "helpdesk-team@acmecorp.com",
                    "resolved_at": "2024-01-26T09:25:00Z",
                },
            },
        },
        "ground_truth": {
            "classification": "false_positive",
            "severity": "low",
            "actions": [],
            "explanation": "Employee returning from approved 2-week vacation (PTO records confirm Jan 12-25). Password expired on Jan 20 while user was away. 5 failed attempts are all from the same registered device, Interactive logon types (physical keyboard, not remote), 30-90 second intervals (human typing speed, not automated). User called helpdesk 3 minutes after lockout, and ticket HD-2026-04-04-0847 confirms the password reset request. This is a routine forgotten/expired password scenario.",
        },
        "relevant_investigations": ["user_profile", "login_history", "device_info", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # BF-04: Monitoring Service Auth Failures -- False Positive, Medium
    # -----------------------------------------------------------------
    {
        "id": "BF-04",
        "difficulty": "medium",
        "alert": {
            "ticket_id": "INC-2024-00298",
            "timestamp": "2024-01-27T06:00:00Z",
            "source_tool": "Splunk SIEM",
            "alert_type": "brute_force",
            "severity_reported": "high",
            "summary": "Potential brute force attack: 4,320 failed authentication attempts detected from IP 10.1.5.50 over the past 6 hours. Single service account svc-nagios-monitor targeted. Attempts span 72 destination servers.",
            "affected_user": "svc-nagios-monitor@acmecorp.com",
            "affected_device": "nagios-prod-01",
            "source_ip": "10.1.5.50",
        },
        "investigation_data": {
            "user_profile": {
                "name": "svc-nagios-monitor (Service Account)",
                "department": "Infrastructure",
                "role": "Nagios Monitoring Service Account",
                "hire_date": "N/A",
                "risk_score": "low",
                "manager": "devops-team@acmecorp.com",
                "access_level": "monitoring-only",
                "mfa_enabled": False,
                "notes": "Service account used by Nagios XI for SNMP/WMI health checks on 72 production servers. Password managed by CyberArk PAM. Last password rotation: 2024-01-26T22:00:00Z (change request CR-2026-1847).",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-27T05:59:00Z", "ip": "10.1.5.50", "target": "web-prod-04", "status": "failed", "reason": "invalid_credentials"},
                    {"timestamp": "2024-01-27T05:58:00Z", "ip": "10.1.5.50", "target": "db-prod-02", "status": "failed", "reason": "invalid_credentials"},
                    {"timestamp": "2024-01-27T05:57:00Z", "ip": "10.1.5.50", "target": "app-prod-07", "status": "failed", "reason": "invalid_credentials"},
                    {"timestamp": "2024-01-27T05:56:00Z", "ip": "10.1.5.50", "target": "web-prod-01", "status": "failed", "reason": "invalid_credentials"},
                ],
                "pattern_analysis": {
                    "total_failures": 4320,
                    "time_window": "6 hours (00:00 — 06:00)",
                    "unique_source_ip": 1,
                    "unique_account": 1,
                    "unique_targets": 72,
                    "interval": "exactly 60 seconds between attempts to each server",
                    "attempts_per_target": 60,
                    "note": "Perfect 60-second interval matches Nagios default check_interval for service checks. Each of the 72 servers is checked once per minute = 72 checks/minute x 60 minutes = 4,320 failures in 6 hours.",
                },
                "summary": "4,320 failures from a single service account (svc-nagios-monitor) to 72 servers at exact 60-second intervals. This is consistent with a Nagios cron-based health check cycle, not an attack. Failures started at 22:00 on Jan 26 — same time CyberArk rotated the service account password.",
            },
            "ip_reputation": {
                "ip": "10.1.5.50",
                "abuse_score": 0,
                "country": "Internal",
                "isp": "AcmeCorp Internal Network",
                "threat_tags": [],
                "note": "Internal IP — Monitoring VLAN. Registered as nagios-prod-01 in CMDB. This is the production Nagios XI monitoring server.",
            },
            "device_info": {
                "device_id": "nagios-prod-01",
                "type": "server",
                "os": "CentOS 8 Stream",
                "last_patch": "2024-01-20",
                "encryption": "LUKS enabled",
                "edr_status": "CrowdStrike active — no threats",
                "registered_owner": "devops-team@acmecorp.com",
                "services_running": ["nagios-xi", "httpd", "mysqld", "npcd"],
                "notes": "Production Nagios XI monitoring server. Monitors 72 servers via WMI/SNMP health checks on 60-second intervals.",
            },
            "email_headers": None,
            "file_analysis": None,
            "network_logs": {
                "connections": [
                    {"timestamp": "2024-01-27T05:59:00Z", "src_ip": "10.1.5.50", "dest_ip": "10.0.3.14", "dest_port": 5666, "protocol": "NRPE", "status": "auth_failed", "service": "Nagios NRPE check"},
                    {"timestamp": "2024-01-27T05:58:00Z", "src_ip": "10.1.5.50", "dest_ip": "10.0.3.22", "dest_port": 5666, "protocol": "NRPE", "status": "auth_failed", "service": "Nagios NRPE check"},
                ],
                "summary": "All connections are NRPE (Nagios Remote Plugin Executor) health checks on port 5666. Perfect 60-second intervals, consistent with nagios check_interval=1m. Traffic pattern unchanged from previous months except failures started after CyberArk password rotation at 22:00.",
                "change_request": {
                    "id": "CR-2026-1847",
                    "type": "Scheduled Password Rotation",
                    "executed": "2024-01-26T22:00:00Z",
                    "account": "svc-nagios-monitor",
                    "system": "CyberArk PAM",
                    "note": "CyberArk rotated the password but the new credential was not synced to the Nagios configuration file (/etc/nagios/resource.cfg). This caused all subsequent health checks to fail authentication.",
                },
            },
            "threat_intel": {
                "campaign": None,
                "mitre_attack": [],
                "related_iocs": [],
                "confidence": "none",
                "advisory": "No threat intelligence matches. Root cause identified: CyberArk PAM rotated svc-nagios-monitor password (CR-2026-1847) at 22:00 on Jan 26 but did not sync the new credential to Nagios config. All 4,320 failures are health check retries using the old password. DevOps updated the Nagios config at 06:15 and failures stopped immediately.",
                "resolution_timeline": {
                    "password_rotated": "2024-01-26T22:00:00Z",
                    "failures_started": "2024-01-26T22:01:00Z",
                    "alert_fired": "2024-01-27T06:00:00Z",
                    "config_updated": "2024-01-27T06:15:00Z",
                    "failures_stopped": "2024-01-27T06:15:00Z",
                },
            },
        },
        "ground_truth": {
            "classification": "false_positive",
            "severity": "low",
            "actions": [],
            "explanation": "Monitoring service (Nagios) auth failures caused by a CyberArk PAM password rotation (CR-2026-1847) that was not synced to the Nagios configuration. 4,320 failures over 6 hours sounds alarming but breaks down to exactly 72 servers x 60 checks/server (one per minute) — perfectly matching Nagios default check intervals. Single source IP (nagios-prod-01), single service account, exact 60-second intervals (cron), NRPE protocol on port 5666. Failures stopped immediately when DevOps updated the Nagios config with the new credential. No attack, no remediation needed beyond the config sync already performed.",
        },
        "relevant_investigations": ["user_profile", "login_history", "ip_reputation", "device_info", "network_logs", "threat_intel"],
    },
]
