"""
Additional phishing scenarios for the Cybersecurity Threat Response Agent.

PH-02 through PH-06: Five phishing-category scenarios ranging from
spear phishing BEC to vendor email compromise.
"""

PHISHING_SCENARIOS = [
    # -----------------------------------------------------------------
    # PH-02: Spear Phishing Executive (CEO Impersonation) — TP, Hard
    # Based on Cosmic Lynx BEC group. Domain typosquatting with "rn" -> "m".
    # -----------------------------------------------------------------
    {
        "id": "PH-02",
        "difficulty": "hard",
        "alert": {
            "ticket_id": "INC-2024-00247",
            "timestamp": "2024-01-22T09:47:00Z",
            "source_tool": "Microsoft Defender",
            "alert_type": "phishing",
            "severity_reported": "medium",
            "summary": "Email from ceo@acrnecorp.com to CFO requesting urgent wire transfer for confidential acquisition. Defender flagged due to newly registered sender domain. User has not yet replied.",
            "affected_user": "deepa.iyer@acmecorp.com",
            "affected_device": "LAPTOP-DI-4010",
            "source_ip": "209.85.167.170",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Deepa Iyer",
                "department": "Finance",
                "role": "Chief Financial Officer",
                "hire_date": "2018-03-01",
                "risk_score": "low",
                "manager": "ceo@acmecorp.com",
                "access_level": "executive",
                "mfa_enabled": True,
                "recent_security_training": "2023-12-15",
                "notes": "C-suite executive. Authorized for wire transfers up to 50 lakhs. Reports directly to CEO Rajesh Khanna.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-22T08:50:00Z", "ip": "10.0.5.20", "location": "Office-Floor5-Executive", "device": "LAPTOP-DI-4010", "status": "success", "mfa": "passed"},
                    {"timestamp": "2024-01-21T09:05:00Z", "ip": "10.0.5.20", "location": "Office-Floor5-Executive", "device": "LAPTOP-DI-4010", "status": "success", "mfa": "passed"},
                ],
                "summary": "Normal executive login pattern. All logins from corporate office on registered device with MFA.",
            },
            "ip_reputation": {
                "ip": "209.85.167.170",
                "abuse_score": 0,
                "country": "US",
                "isp": "Google LLC",
                "threat_tags": [],
                "last_reported": None,
                "virustotal_detections": "0/90 engines flagged",
                "first_seen": "2012-04-15",
                "note": "Legitimate Google mail server (mail-yw1-f170.google.com). Used by Google Workspace accounts. Clean reputation because attacker uses Google Workspace for sending.",
            },
            "device_info": {
                "device_id": "LAPTOP-DI-4010",
                "type": "laptop",
                "os": "Windows 11 Pro 23H2",
                "last_patch": "2024-01-18",
                "encryption": "BitLocker enabled",
                "edr_status": "Microsoft Defender active — no threats detected",
                "registered_owner": "deepa.iyer@acmecorp.com",
                "last_scan": "2024-01-22T06:00:00Z",
            },
            "email_headers": {
                "from": "Rajesh Khanna <ceo@acrnecorp.com>",
                "reply_to": "rajesh.khanna.private@proton.me",
                "sender_ip": "209.85.167.170",
                "spf": "pass",
                "dkim": "pass",
                "dmarc": "none",
                "received_chain": [
                    "from mail-yw1-f170.google.com (209.85.167.170)",
                    "by mx.acmecorp.com (10.0.1.5)",
                ],
                "subject": "Confidential — Urgent Wire Transfer Required",
                "url_in_body": None,
                "attachment": None,
                "ssl_cert_age": "3 days (issued 2024-01-19, Let's Encrypt)",
                "domain_registration": {
                    "domain": "acrnecorp.com",
                    "registrar": "Namecheap Inc.",
                    "created": "2024-01-19",
                    "registrant_country": "RU",
                    "nameservers": ["ns1.google.com", "ns2.google.com"],
                },
                "body_snippet": "Deepa, I need you to process a wire transfer of 42,00,000 INR to the account below for a confidential acquisition. This must be completed today. Do not discuss with anyone — legal sensitivity. I am in meetings all day so email me at my personal address if you have questions.",
            },
            "file_analysis": None,
            "network_logs": {
                "connections": [],
                "summary": "No outbound connections related to this email. User has not clicked any links or replied yet.",
            },
            "threat_intel": {
                "campaign": "Cosmic Lynx BEC — Russian business email compromise group targeting C-suite executives with CEO impersonation via typosquatted domains",
                "mitre_attack": ["T1566.002 (Spearphishing Link)", "T1656 (Impersonation)", "T1583.001 (Acquire Infrastructure: Domains)"],
                "related_iocs": ["acrnecorp.com", "rajesh.khanna.private@proton.me"],
                "threat_actor": "Cosmic Lynx",
                "confidence": "high",
                "advisory": "Cosmic Lynx is known for registering lookalike domains where 'rn' substitutes for 'm' (acrnecorp vs acmecorp). They configure legitimate SPF/DKIM on attacker-controlled domains to pass email authentication. Reply-To always diverges to a freemail address. Domain age and Reply-To mismatch are primary detection indicators.",
                "virustotal": "3/90 detections for acrnecorp.com — flagged by Kaspersky, ESET, and Fortinet as phishing domain",
            },
        },
        "ground_truth": {
            "classification": "true_positive",
            "severity": "critical",
            "actions": ["block_sender_ip", "quarantine_email", "reset_user_password", "send_employee_alert", "notify_manager", "escalate_to_tier2"],
            "explanation": "CEO impersonation BEC attack using typosquatted domain acrnecorp.com (rn mimics m). SPF/DKIM pass because the attacker configured them on the lookalike domain — this is the deceptive part. Key indicators: (1) domain registered 3 days ago on Namecheap with Russian registrant, (2) Reply-To diverges to proton.me personal address, (3) DMARC=none means no policy enforcement, (4) urgency + secrecy + wire transfer request is classic BEC playbook. Domain has 3/90 VT detections. Cosmic Lynx attribution. Critical severity due to potential financial loss of 42 lakhs INR.",
        },
        "relevant_investigations": ["email_headers", "threat_intel", "user_profile", "ip_reputation"],
    },

    # -----------------------------------------------------------------
    # PH-03: Marketing Email Flagged (Legitimate Mailchimp) — FP, Easy
    # -----------------------------------------------------------------
    {
        "id": "PH-03",
        "difficulty": "easy",
        "alert": {
            "ticket_id": "INC-2024-00261",
            "timestamp": "2024-01-23T11:15:00Z",
            "source_tool": "Proofpoint",
            "alert_type": "phishing",
            "severity_reported": "medium",
            "summary": "Email from SaaS vendor 'CloudStack Solutions' flagged by Proofpoint URL Defense due to multiple tracking redirects in email body. Links rewrite through Mailchimp click-tracking infrastructure.",
            "affected_user": "vikram.mehta@acmecorp.com",
            "affected_device": "LAPTOP-VM-2205",
            "source_ip": "198.2.135.234",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Vikram Mehta",
                "department": "Finance",
                "role": "Finance Director",
                "hire_date": "2019-02-15",
                "risk_score": "low",
                "manager": "deepa.iyer@acmecorp.com",
                "access_level": "manager",
                "mfa_enabled": True,
                "recent_security_training": "2023-11-20",
                "notes": "Subscribed to multiple SaaS vendor newsletters. Previously reported as FP recipient in INC-2023-01820.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-23T09:02:00Z", "ip": "10.0.12.50", "location": "Office-Floor2", "device": "LAPTOP-VM-2205", "status": "success", "mfa": "passed"},
                ],
                "summary": "Normal office login. No anomalies.",
            },
            "ip_reputation": {
                "ip": "198.2.135.234",
                "abuse_score": 0,
                "country": "US",
                "isp": "The Rocket Science Group LLC (Mailchimp)",
                "asn": "AS46606",
                "threat_tags": [],
                "last_reported": None,
                "virustotal_detections": "0/90 engines flagged",
                "first_seen": "2015-06-10",
                "note": "Mailchimp bulk-sending infrastructure. Legitimate email marketing platform. AS46606 is registered to Intuit/Mailchimp.",
            },
            "device_info": {
                "device_id": "LAPTOP-VM-2205",
                "type": "laptop",
                "os": "Windows 11 Pro 23H2",
                "last_patch": "2024-01-20",
                "encryption": "BitLocker enabled",
                "edr_status": "Microsoft Defender active — no threats detected",
                "registered_owner": "vikram.mehta@acmecorp.com",
                "last_scan": "2024-01-23T06:00:00Z",
            },
            "email_headers": {
                "from": "CloudStack Solutions <updates@mail.cloudstacksolutions.com>",
                "reply_to": "support@cloudstacksolutions.com",
                "sender_ip": "198.2.135.234",
                "spf": "pass",
                "dkim": "pass (dual signature: cloudstacksolutions.com + mailchimp.com)",
                "dmarc": "pass",
                "received_chain": [
                    "from mail234.suw17.rsgsv.net (198.2.135.234)",
                    "by mx.acmecorp.com (10.0.1.5)",
                ],
                "subject": "Q1 Product Updates & New Integrations from CloudStack",
                "url_in_body": "https://cloudstacksolutions.us14.list-manage.com/track/click?u=a8b9c0d1e2&id=f3g4h5i6j7",
                "attachment": None,
                "custom_headers": {
                    "X-MC-User": "a8b9c0d1e2f3a4b5c6d7e8f9",
                    "X-Mailchimp-Unique": "mc_2024012311150023",
                    "List-Unsubscribe": "<https://cloudstacksolutions.us14.list-manage.com/unsubscribe?u=a8b9c0d1e2&id=k8l9m0n1>",
                    "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
                    "X-Mailer": "Mailchimp Mailer",
                    "Feedback-ID": "123456:mc",
                },
                "ssl_cert_age": "Valid certificate, issued 2023-08-15 by DigiCert",
            },
            "file_analysis": None,
            "network_logs": {
                "connections": [],
                "summary": "No suspicious outbound connections. User has not clicked any links in the email.",
            },
            "threat_intel": {
                "campaign": None,
                "mitre_attack": [],
                "related_iocs": [],
                "confidence": "none",
                "advisory": "No threat intelligence matches. Sender IP belongs to Mailchimp infrastructure (AS46606). CloudStack Solutions is a known SaaS vendor with legitimate marketing campaigns. Proofpoint flagged due to URL rewrite/tracking redirect heuristics — a common false positive with marketing platforms.",
            },
        },
        "ground_truth": {
            "classification": "false_positive",
            "severity": "low",
            "actions": [],
            "explanation": "Legitimate Mailchimp marketing email from a known SaaS vendor. All email authentication passes (SPF, DKIM with dual signatures, DMARC). Sending IP 198.2.135.234 is clean Mailchimp infrastructure (AS46606). Headers contain standard Mailchimp identifiers (X-MC-User, X-Mailchimp-Unique, List-Unsubscribe-Post). Proofpoint flagged the tracking redirects as suspicious — this is a well-known false positive pattern with marketing email platforms. No action required.",
        },
        "relevant_investigations": ["email_headers", "ip_reputation", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # PH-04: Credential Harvest Page (Fake O365 Login) — TP, Medium
    # Based on Storm-1575 / Greatness PaaS.
    # -----------------------------------------------------------------
    {
        "id": "PH-04",
        "difficulty": "medium",
        "alert": {
            "ticket_id": "INC-2024-00278",
            "timestamp": "2024-01-24T16:05:00Z",
            "source_tool": "Proofpoint",
            "alert_type": "phishing",
            "severity_reported": "high",
            "summary": "Email purporting to be a SharePoint document share with link to login-microsoftonline.com-auth.xyz. Proofpoint TAP flagged sender IP and URL. User clicked link but did not submit credentials (no POST request observed).",
            "affected_user": "ananya.das@acmecorp.com",
            "affected_device": "LAPTOP-AD-3307",
            "source_ip": "94.131.107.42",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Ananya Das",
                "department": "Human Resources",
                "role": "HR Manager",
                "hire_date": "2020-11-15",
                "risk_score": "low",
                "manager": "sunita.verma@acmecorp.com",
                "access_level": "manager",
                "mfa_enabled": True,
                "recent_security_training": "2024-01-05",
                "notes": "Has access to employee PII and salary data. Recently completed phishing awareness refresher course.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-24T09:10:00Z", "ip": "10.0.10.33", "location": "Office-Floor3", "device": "LAPTOP-AD-3307", "status": "success", "mfa": "passed"},
                    {"timestamp": "2024-01-23T09:05:00Z", "ip": "10.0.10.33", "location": "Office-Floor3", "device": "LAPTOP-AD-3307", "status": "success", "mfa": "passed"},
                ],
                "summary": "Normal office logins. No anomalies in login pattern. No logins from unusual locations.",
            },
            "ip_reputation": {
                "ip": "94.131.107.42",
                "abuse_score": 78,
                "country": "MD",
                "isp": "Stark Industries Solutions Ltd",
                "threat_tags": ["phishing-infrastructure", "bulletproof-hosting", "credential-harvesting"],
                "last_reported": "2024-01-23",
                "virustotal_detections": "2/90 engines flagged as malicious (initial scan)",
                "first_seen": "2023-11-20",
                "associated_domains": ["login-microsoftonline.com-auth.xyz", "sharepoint-docs-view.com", "ms365-secure-login.net"],
                "note": "Stark Industries Solutions is a known bulletproof hosting provider based in Moldova, frequently used by phishing operators.",
            },
            "device_info": {
                "device_id": "LAPTOP-AD-3307",
                "type": "laptop",
                "os": "Windows 11 Pro 23H2",
                "last_patch": "2024-01-19",
                "encryption": "BitLocker enabled",
                "edr_status": "Microsoft Defender active — no threats detected on device",
                "registered_owner": "ananya.das@acmecorp.com",
                "last_scan": "2024-01-24T06:00:00Z",
            },
            "email_headers": {
                "from": "SharePoint Online <noreply@login-microsoftonline.com-auth.xyz>",
                "reply_to": "noreply@login-microsoftonline.com-auth.xyz",
                "sender_ip": "94.131.107.42",
                "spf": "fail",
                "dkim": "none",
                "dmarc": "fail",
                "received_chain": [
                    "from mail.login-microsoftonline.com-auth.xyz (94.131.107.42)",
                    "by mx.acmecorp.com (10.0.1.5)",
                ],
                "subject": "Sunita Verma shared 'Q1 Performance Reviews.xlsx' with you",
                "url_in_body": "https://login-microsoftonline.com-auth.xyz/signin?client_id=acmecorp&redirect=sharepoint",
                "attachment": None,
                "ssl_cert_age": "1 day (issued 2024-01-23, Let's Encrypt)",
                "domain_registration": {
                    "domain": "login-microsoftonline.com-auth.xyz",
                    "registrar": "Porkbun LLC",
                    "created": "2024-01-22",
                    "registrant_country": "Privacy Protected",
                    "nameservers": ["ns1.porkbun.com", "ns2.porkbun.com"],
                },
            },
            "file_analysis": None,
            "network_logs": {
                "connections": [
                    {"timestamp": "2024-01-24T16:05:30Z", "dest_ip": "94.131.107.42", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 450, "bytes_received": 28000, "duration": "8s", "note": "GET request only — page loaded but no form submission detected"},
                ],
                "dns_queries": [
                    {"timestamp": "2024-01-24T16:05:25Z", "domain": "login-microsoftonline.com-auth.xyz", "resolved_ip": "94.131.107.42"},
                ],
                "summary": "User clicked link and loaded the phishing page (28KB received — typical for a credential harvesting page). Only 450 bytes sent (GET request headers). No POST request with credentials detected. User likely recognized the fake page and closed it.",
            },
            "threat_intel": {
                "campaign": "Storm-1575 / Greatness Phishing-as-a-Service — credential harvesting kit targeting Microsoft 365 users with realistic login clones",
                "mitre_attack": ["T1566.002 (Spearphishing Link)", "T1598.003 (Phishing for Information: Spearphishing Link)"],
                "related_iocs": ["94.131.107.42", "login-microsoftonline.com-auth.xyz", "sharepoint-docs-view.com", "ms365-secure-login.net"],
                "threat_actor": "Storm-1575",
                "confidence": "high",
                "advisory": "Greatness PaaS provides turnkey phishing kits that clone Microsoft 365 login pages with real-time credential relay. Hosted on Stark Industries bulletproof infrastructure in Moldova. SSL cert is 1 day old via Let's Encrypt. Even though SPF/DKIM/DMARC all fail, the realistic SharePoint notification format can deceive users.",
            },
        },
        "ground_truth": {
            "classification": "true_positive",
            "severity": "high",
            "actions": ["block_sender_ip", "quarantine_email", "reset_user_password", "send_employee_alert"],
            "explanation": "Credential harvesting phishing using fake Microsoft 365 login page. Clear indicators: SPF fail, no DKIM, DMARC fail. Sender IP 94.131.107.42 is Stark Industries bulletproof hosting in Moldova (abuse score 78). Domain registered 2 days ago with 1-day-old Let's Encrypt cert. Storm-1575/Greatness PaaS attribution. User clicked the link but network logs show no POST request (no credential submission). Password reset is precautionary. Block sender IP and quarantine email to prevent other recipients from clicking.",
        },
        "relevant_investigations": ["email_headers", "ip_reputation", "network_logs", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # PH-05: Internal Phishing Test (IT Security Simulation) — FP, Medium
    # KnowBe4 platform simulation.
    # -----------------------------------------------------------------
    {
        "id": "PH-05",
        "difficulty": "medium",
        "alert": {
            "ticket_id": "INC-2024-00295",
            "timestamp": "2024-01-25T10:30:00Z",
            "source_tool": "Microsoft Defender",
            "alert_type": "phishing",
            "severity_reported": "medium",
            "summary": "Email impersonating IT helpdesk requesting password verification via external link. Defender ATP flagged the URL as suspicious. Multiple users across the organization received identical emails within a 5-minute window.",
            "affected_user": "rohan.gupta@acmecorp.com",
            "affected_device": "LAPTOP-RG-5502",
            "source_ip": "147.160.167.43",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Rohan Gupta",
                "department": "Engineering",
                "role": "Frontend Developer",
                "hire_date": "2022-08-01",
                "risk_score": "low",
                "manager": "neha.joshi@acmecorp.com",
                "access_level": "developer",
                "mfa_enabled": True,
                "recent_security_training": "2023-12-01",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-25T09:15:00Z", "ip": "10.0.15.42", "location": "Office-Floor4", "device": "LAPTOP-RG-5502", "status": "success", "mfa": "passed"},
                ],
                "summary": "Normal office login. No anomalies.",
            },
            "ip_reputation": {
                "ip": "147.160.167.43",
                "abuse_score": 0,
                "country": "US",
                "isp": "KnowBe4 Inc.",
                "threat_tags": [],
                "last_reported": None,
                "virustotal_detections": "0/90 engines flagged",
                "first_seen": "2019-02-10",
                "note": "KnowBe4 phishing simulation platform IP range (147.160.167.0/24). Used by enterprise security teams for authorized phishing awareness testing.",
            },
            "device_info": {
                "device_id": "LAPTOP-RG-5502",
                "type": "laptop",
                "os": "macOS Sonoma 14.2",
                "last_patch": "2024-01-20",
                "encryption": "FileVault enabled",
                "edr_status": "CrowdStrike Falcon active — no threats",
                "registered_owner": "rohan.gupta@acmecorp.com",
                "last_scan": "2024-01-25T06:00:00Z",
            },
            "email_headers": {
                "from": "IT Helpdesk <helpdesk@acmecorp.com>",
                "reply_to": "helpdesk@acmecorp.com",
                "sender_ip": "147.160.167.43",
                "spf": "pass (for psm.knowbe4.com)",
                "dkim": "pass",
                "dmarc": "pass",
                "received_chain": [
                    "from psm2023.knowbe4.com (147.160.167.43)",
                    "by mx.acmecorp.com (10.0.1.5)",
                ],
                "subject": "ACTION REQUIRED: Verify Your Password Before Account Lockout",
                "url_in_body": "https://training.knowbe4.com/simulated-phishing/acmecorp/verify?uid=rg5502",
                "attachment": None,
                "custom_headers": {
                    "X-PHISHTEST": "KB4-SIM-2024-01-25-ACME-042",
                    "X-KB4-Tracking": "campaign_id=4821;user_id=rg5502;template=password_expiry_v3",
                    "X-Mailer": "KnowBe4 Phishing Simulator",
                    "Return-Path": "bounce-rg5502@psm.knowbe4.com",
                },
                "ssl_cert_age": "Valid certificate, issued 2023-06-01 by Amazon RSA 2048 M02",
            },
            "file_analysis": None,
            "network_logs": {
                "connections": [],
                "summary": "No outbound connections to suspicious destinations. User has not clicked the link.",
            },
            "threat_intel": {
                "campaign": None,
                "mitre_attack": [],
                "related_iocs": [],
                "confidence": "none",
                "advisory": "Sender IP 147.160.167.43 belongs to KnowBe4 phishing simulation platform. Headers contain X-PHISHTEST and X-KB4-Tracking identifiers consistent with authorized security awareness testing. AcmeCorp IT Security team has an active KnowBe4 license (contract ref: KB4-ACME-2023-ENT). This appears to be a scheduled phishing simulation, not a real attack.",
            },
        },
        "ground_truth": {
            "classification": "false_positive",
            "severity": "low",
            "actions": [],
            "explanation": "This is an authorized internal phishing simulation run by AcmeCorp's IT Security team using the KnowBe4 platform. Key indicators: (1) sender IP 147.160.167.43 is registered KnowBe4 infrastructure, (2) email headers contain X-PHISHTEST and X-KB4-Tracking simulation identifiers, (3) Return-Path points to psm.knowbe4.com, (4) URL domain is training.knowbe4.com (not a malicious clone), (5) multiple employees received identical emails simultaneously (batch send pattern typical of simulation campaigns). No action required — this is an authorized security awareness test.",
        },
        "relevant_investigations": ["email_headers", "ip_reputation", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # PH-06: Compromised Vendor Email (Real Mailbox, Malicious Macro) — TP, Hard
    # Based on TA505 / Silent Starling vendor email compromise.
    # -----------------------------------------------------------------
    {
        "id": "PH-06",
        "difficulty": "hard",
        "alert": {
            "ticket_id": "INC-2024-00312",
            "timestamp": "2024-01-26T14:20:00Z",
            "source_tool": "Microsoft Defender",
            "alert_type": "phishing",
            "severity_reported": "low",
            "summary": "Email from known vendor contact at Pinnacle Consulting (sanjay.menon@pinnacleconsulting.in) with .xlsm attachment. Defender flagged macro-enabled spreadsheet. Vendor is a regular supplier — Finance team expects invoices from this contact.",
            "affected_user": "priya.sharma@acmecorp.com",
            "affected_device": "LAPTOP-PS-3201",
            "source_ip": "40.107.22.135",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Priya Sharma",
                "department": "Finance",
                "role": "Senior Accountant",
                "hire_date": "2021-06-15",
                "risk_score": "low",
                "manager": "vikram.mehta@acmecorp.com",
                "access_level": "standard",
                "mfa_enabled": True,
                "recent_security_training": "2023-11-01",
                "notes": "Regularly processes invoices from Pinnacle Consulting. Has received legitimate emails from sanjay.menon@pinnacleconsulting.in at least 15 times in the past 6 months.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2024-01-26T09:00:00Z", "ip": "10.0.12.45", "location": "Office-Floor2", "device": "LAPTOP-PS-3201", "status": "success", "mfa": "passed"},
                    {"timestamp": "2024-01-25T09:05:00Z", "ip": "10.0.12.45", "location": "Office-Floor2", "device": "LAPTOP-PS-3201", "status": "success", "mfa": "passed"},
                ],
                "summary": "Normal office logins. No anomalies. Same pattern as always.",
            },
            "ip_reputation": {
                "ip": "40.107.22.135",
                "abuse_score": 0,
                "country": "US",
                "isp": "Microsoft Corporation",
                "threat_tags": [],
                "last_reported": None,
                "virustotal_detections": "0/90 engines flagged",
                "first_seen": "2018-01-15",
                "note": "Microsoft 365 mail infrastructure (mail-eopbgr220135.outbound.protection.outlook.com). Legitimate mail server used by millions of organizations. This is the real Pinnacle Consulting mail server — their mailbox was compromised, not spoofed.",
            },
            "device_info": {
                "device_id": "LAPTOP-PS-3201",
                "type": "laptop",
                "os": "Windows 11 Pro 23H2",
                "last_patch": "2024-01-22",
                "encryption": "BitLocker enabled",
                "edr_status": "Microsoft Defender active — macro execution blocked by policy, file quarantined",
                "registered_owner": "priya.sharma@acmecorp.com",
                "last_scan": "2024-01-26T06:00:00Z",
                "notes": "User attempted to open attachment. Macro was blocked by Defender ASR rule. File placed in quarantine.",
            },
            "email_headers": {
                "from": "Sanjay Menon <sanjay.menon@pinnacleconsulting.in>",
                "reply_to": "sanjay.menon@pinnacleconsulting.in",
                "sender_ip": "40.107.22.135",
                "spf": "pass",
                "dkim": "pass",
                "dmarc": "pass",
                "received_chain": [
                    "from mail-eopbgr220135.outbound.protection.outlook.com (40.107.22.135)",
                    "by mx.acmecorp.com (10.0.1.5)",
                ],
                "subject": "Updated Invoice — Q1 Consulting Services (Pinnacle Ref: PC-2024-0891)",
                "url_in_body": None,
                "attachment": "Q1_Invoice_Pinnacle_Updated.xlsm (287 KB, macro-enabled Excel spreadsheet)",
                "ssl_cert_age": "Valid certificate, Microsoft managed",
                "notes": "All email authentication passes because this is the REAL vendor mailbox. The vendor's Microsoft 365 account was compromised by the attacker. Email appears entirely legitimate at the header level.",
            },
            "file_analysis": {
                "filename": "Q1_Invoice_Pinnacle_Updated.xlsm",
                "hash_sha256": "e7c4a9d2f1b8e3a5c6d9f0a2b4e7c1d3f5a8b0c2e4d6f8a1b3c5d7e9f0a2b4c6",
                "file_size": "287 KB",
                "file_type": "Microsoft Excel Macro-Enabled Spreadsheet (.xlsm)",
                "signed": False,
                "virustotal_detections": "4/72 engines detected as malicious (initial scan — 38/72 after 3 days)",
                "detection_names": ["VBA/Agent.NXR", "Trojan.Downloader.XLS.Gen", "VBA.Trojan.Downloader", "Heur:Trojan.Script.Generic"],
                "behavioral_analysis": {
                    "macro_analysis": {
                        "obfuscated": True,
                        "auto_open": True,
                        "calls_shell": True,
                        "downloads_payload": True,
                        "payload_url": "https://cdn-updates.azurewebsites.net/api/v2/update-check",
                        "payload_type": "DLL sideloading via rundll32.exe",
                        "sandbox_evasion": ["checks for VM artifacts", "delays execution by 120 seconds", "checks mouse movement"],
                    },
                    "c2_communication": {
                        "primary_c2": "cdn-updates.azurewebsites.net",
                        "c2_ip": "185.70.184.8",
                        "c2_isp": "M247 Ltd",
                        "c2_country": "RO",
                        "protocol": "HTTPS",
                        "beacon_interval": "300 seconds",
                    },
                },
                "iocs": ["cdn-updates.azurewebsites.net", "185.70.184.8", "e7c4a9d2f1b8e3a5c6d9f0a2b4e7c1d3f5a8b0c2e4d6f8a1b3c5d7e9f0a2b4c6"],
                "first_seen_in_wild": "2024-01-25",
                "note": "Low initial VT detection (4/72) is consistent with newly crafted malware. The .xlsm file type is unusual for invoice delivery — legitimate invoices from this vendor are typically .pdf or .xlsx.",
            },
            "network_logs": {
                "connections": [
                    {"timestamp": "2024-01-26T14:22:00Z", "dest_ip": "185.70.184.8", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 0, "bytes_received": 0, "duration": "0s", "status": "blocked", "note": "Outbound connection attempt to cdn-updates.azurewebsites.net blocked by Defender — macro execution was prevented"},
                ],
                "dns_queries": [
                    {"timestamp": "2024-01-26T14:21:55Z", "domain": "cdn-updates.azurewebsites.net", "resolved_ip": "185.70.184.8"},
                ],
                "summary": "DNS resolution for C2 domain occurred (triggered by macro pre-fetch) but actual connection was blocked by Defender ASR policy. No payload was downloaded. No successful C2 communication.",
            },
            "threat_intel": {
                "campaign": "TA505 / Silent Starling — vendor email compromise campaign targeting finance teams via compromised supplier mailboxes with macro-enabled documents",
                "mitre_attack": ["T1199 (Trusted Relationship)", "T1566.001 (Spearphishing Attachment)", "T1204.002 (User Execution: Malicious File)"],
                "related_iocs": ["cdn-updates.azurewebsites.net", "185.70.184.8", "e7c4a9d2f1b8e3a5c6d9f0a2b4e7c1d3f5a8b0c2e4d6f8a1b3c5d7e9f0a2b4c6"],
                "threat_actor": "TA505 / Silent Starling",
                "confidence": "high",
                "advisory": "TA505 compromises vendor Microsoft 365 mailboxes and sends malicious attachments from the real vendor email address. All email authentication (SPF/DKIM/DMARC) passes because the email originates from the legitimate vendor infrastructure. Detection relies on attachment analysis: (1) .xlsm file type is unusual for invoices, (2) macro contains obfuscated VBA with auto-open, (3) C2 domain uses Azure Web App to blend with legitimate Microsoft traffic. Pinnacle Consulting should be notified that their mailbox has been compromised.",
                "virustotal_c2": "cdn-updates.azurewebsites.net — 6/90 detections. Hosted on Azure (attacker-controlled). IP 185.70.184.8 mapped via M247 Ltd (Romania) — known for hosting C2 infrastructure.",
            },
        },
        "ground_truth": {
            "classification": "true_positive",
            "severity": "critical",
            "actions": ["quarantine_email", "quarantine_file", "block_ip", "isolate_device", "send_employee_alert", "notify_manager", "escalate_to_tier2"],
            "explanation": "Vendor email compromise — the attacker compromised Pinnacle Consulting's real Microsoft 365 mailbox and sent a malicious macro-enabled spreadsheet from the legitimate address. This is extremely dangerous because all email authentication (SPF/DKIM/DMARC) passes and the sender is a known trusted contact. Key detection indicators: (1) .xlsm file type is abnormal for invoice delivery from this vendor, (2) file contains obfuscated auto-open VBA macro with shell execution and payload download, (3) C2 domain cdn-updates.azurewebsites.net resolves to 185.70.184.8 (M247 Ltd, Romania), (4) initial VT detection is low (4/72) indicating fresh malware. Defender blocked macro execution. Critical severity: isolate the device for forensics, block C2 IP, quarantine email across all recipients, notify the vendor that their mailbox is compromised, escalate for org-wide threat hunt.",
        },
        "relevant_investigations": ["email_headers", "file_analysis", "network_logs", "threat_intel", "user_profile"],
    },
]
