"""
Login-specific scenarios for the Cybersecurity Threat Response Agent.

5 suspicious-login scenarios covering impossible travel, credential stuffing,
business travel FP, service account abuse, and new device enrollment FP.
"""

LOGIN_SCENARIOS = [
    # -----------------------------------------------------------------
    # SL-01: Impossible Travel (NYC -> Lagos in 32 min) -- TP, Medium
    # -----------------------------------------------------------------
    {
        "id": "SL-01",
        "difficulty": "medium",
        "alert": {
            "ticket_id": "INC-2026-04201",
            "timestamp": "2026-04-03T16:47:00Z",
            "source_tool": "Azure Sentinel",
            "alert_type": "suspicious_login",
            "severity_reported": "high",
            "summary": "Impossible travel detected for user rohit.deshmukh@acmecorp.com. Successful login from New York, US at 16:15 UTC followed by successful login from Lagos, Nigeria at 16:47 UTC (32 minutes apart). Geographic distance makes physical travel impossible.",
            "affected_user": "rohit.deshmukh@acmecorp.com",
            "affected_device": "LAPTOP-RD-2204",
            "source_ip": "105.112.191.217",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Rohit Deshmukh",
                "department": "Product Management",
                "role": "Senior Product Manager",
                "hire_date": "2020-03-10",
                "risk_score": "low",
                "manager": "sunita.kulkarni@acmecorp.com",
                "access_level": "standard",
                "mfa_enabled": True,
                "recent_security_training": "2026-01-20",
                "notes": "Currently on business trip to New York office. No travel to Africa planned.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2026-04-03T16:47:00Z", "ip": "105.112.191.217", "location": "Lagos, Nigeria", "device": "Unknown — browser fingerprint mismatch", "status": "success", "mfa": "passed (push notification)", "session_token": "eyJ0eX...stolen"},
                    {"timestamp": "2026-04-03T16:15:00Z", "ip": "74.101.36.142", "location": "New York, US", "device": "LAPTOP-RD-2204", "status": "success", "mfa": "passed"},
                    {"timestamp": "2026-04-03T09:02:00Z", "ip": "74.101.36.142", "location": "New York, US", "device": "LAPTOP-RD-2204", "status": "success", "mfa": "passed"},
                    {"timestamp": "2026-04-02T14:30:00Z", "ip": "74.101.36.142", "location": "New York, US", "device": "LAPTOP-RD-2204", "status": "success", "mfa": "passed"},
                ],
                "summary": "Consistent logins from New York since April 2 (business trip). Lagos login at 16:47 UTC uses a different device fingerprint and a replayed session token. MFA was not truly re-verified — session token was reused from an AiTM phishing attack.",
            },
            "ip_reputation": {
                "ip": "105.112.191.217",
                "abuse_score": 38,
                "country": "NG",
                "isp": "Airtel Networks Limited",
                "asn": "AS36873",
                "threat_tags": ["proxy-usage", "suspicious-auth"],
                "last_reported": "2026-03-28",
                "virustotal_detections": "3/87 engines flagged",
                "first_seen": "2019-11-05",
                "note": "Mobile ISP in Lagos, Nigeria. Moderate abuse score — used in prior credential abuse campaigns.",
            },
            "device_info": {
                "device_id": "LAPTOP-RD-2204",
                "type": "laptop",
                "os": "macOS 15.3 Sequoia",
                "last_patch": "2026-03-28",
                "encryption": "FileVault enabled",
                "edr_status": "CrowdStrike Falcon active — no threats detected",
                "registered_owner": "rohit.deshmukh@acmecorp.com",
                "last_scan": "2026-04-03T07:00:00Z",
                "intune_compliant": True,
                "note": "The Lagos login did NOT originate from this device. Browser user-agent differs: Chrome 124 on Windows 10 vs Safari 18 on macOS (registered device).",
            },
            "email_headers": None,
            "file_analysis": None,
            "network_logs": {
                "connections": [
                    {"timestamp": "2026-04-03T16:48:00Z", "src_ip": "105.112.191.217", "dest_ip": "13.107.42.11", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 3200, "bytes_received": 890000, "duration": "8m", "service": "SharePoint Online"},
                    {"timestamp": "2026-04-03T16:56:00Z", "src_ip": "105.112.191.217", "dest_ip": "40.104.36.210", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 1800, "bytes_received": 4500, "duration": "2m", "service": "Exchange Online — Inbox Rule Creation"},
                ],
                "summary": "Post-compromise activity from Lagos IP: accessed SharePoint Online and downloaded files, then created inbox rule in Exchange Online to auto-delete emails with subjects containing 'security', 'password reset', 'unauthorized', and 'MFA'.",
            },
            "threat_intel": {
                "campaign": "Storm-0558 variant — AiTM phishing with session token theft targeting enterprise M365 tenants",
                "mitre_attack": ["T1078.004 (Valid Accounts: Cloud Accounts)", "T1539 (Steal Web Session Cookie)", "T1556.006 (Modify Authentication Process: Multi-Factor Authentication)"],
                "related_iocs": ["105.112.191.217", "aitm-login-microsft[.]com"],
                "threat_actor": "Storm-0558 affiliated",
                "confidence": "high",
                "advisory": "AiTM phishing campaign stealing session tokens to bypass MFA. Attacker replays stolen session cookies from geographically distant locations. Post-compromise actions include inbox rule creation to hide security alerts and SharePoint data access.",
            },
        },
        "ground_truth": {
            "classification": "true_positive",
            "severity": "high",
            "actions": ["disable_user_account", "reset_user_password", "send_employee_alert", "notify_manager", "escalate_to_tier2"],
            "explanation": "Impossible travel: NYC to Lagos in 32 minutes is physically impossible. The Lagos login used a different device fingerprint (Chrome/Windows vs Safari/macOS) and a replayed session token from an AiTM phishing attack. Post-compromise activity confirms malicious intent: SharePoint data access and inbox rule hiding security emails. User account must be disabled immediately, password reset, and escalated for full incident response including session token revocation.",
        },
        "relevant_investigations": ["login_history", "ip_reputation", "device_info", "network_logs", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # SL-03: Credential Stuffing (47K fails, rotating IPs) -- TP, Hard
    # -----------------------------------------------------------------
    {
        "id": "SL-03",
        "difficulty": "hard",
        "alert": {
            "ticket_id": "INC-2026-04215",
            "timestamp": "2026-04-04T08:30:00Z",
            "source_tool": "Azure Sentinel",
            "alert_type": "suspicious_login",
            "severity_reported": "medium",
            "summary": "Suspicious login activity detected for user kavita.joshi@acmecorp.com. Account password was changed and a new email forwarding rule was created. User's credentials may have been compromised in a broader credential stuffing campaign (47,832 failed attempts observed across 12,408 accounts in the past 6 hours).",
            "affected_user": "kavita.joshi@acmecorp.com",
            "affected_device": "Unknown",
            "source_ip": "45.33.32.156",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Kavita Joshi",
                "department": "Human Resources",
                "role": "HR Business Partner",
                "hire_date": "2019-07-22",
                "risk_score": "low",
                "manager": "deepak.patil@acmecorp.com",
                "access_level": "standard",
                "mfa_enabled": True,
                "recent_security_training": "2025-12-10",
                "notes": "Has access to employee PII data, compensation records, and HR systems. Uses the same email/password combination across personal accounts (disclosed in prior security awareness survey).",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2026-04-04T07:58:00Z", "ip": "45.33.32.156", "location": "Fremont, US", "device": "Unknown — no Intune enrollment", "status": "success", "mfa": "passed (SMS)", "ja3_fingerprint": "e7d705a3286e19ea42f587b344ee6865", "note": "Successful login after 3 prior failures on this account"},
                    {"timestamp": "2026-04-04T07:55:00Z", "ip": "185.220.101.34", "location": "Tor Exit Node, DE", "device": "Unknown", "status": "failed", "ja3_fingerprint": "e7d705a3286e19ea42f587b344ee6865"},
                    {"timestamp": "2026-04-04T07:52:00Z", "ip": "198.44.136.78", "location": "Roubaix, FR", "device": "Unknown", "status": "failed", "ja3_fingerprint": "e7d705a3286e19ea42f587b344ee6865"},
                    {"timestamp": "2026-04-04T07:49:00Z", "ip": "45.33.32.156", "location": "Fremont, US", "device": "Unknown", "status": "failed", "ja3_fingerprint": "e7d705a3286e19ea42f587b344ee6865"},
                    {"timestamp": "2026-04-03T09:00:00Z", "ip": "10.0.18.92", "location": "Office-Floor5", "device": "DESKTOP-KJ-0803", "status": "success", "mfa": "passed"},
                ],
                "summary": "Three failed login attempts from rotating IPs (Linode, Tor exit, OVH) followed by successful login from Linode IP. All failed/successful attempts share the same TLS JA3 fingerprint (e7d705a3286e19ea42f587b344ee6865 — Python httpx client), indicating automated tooling. The attack stayed below the 5-attempt lockout threshold per account. This is one of 99 accounts compromised out of 12,408 targeted (0.8% success rate). 47,832 total failed attempts across all accounts in 6 hours.",
            },
            "ip_reputation": {
                "ip": "45.33.32.156",
                "abuse_score": 67,
                "country": "US",
                "isp": "Akamai Connected Cloud (Linode)",
                "asn": "AS63949",
                "threat_tags": ["credential-stuffing", "automated-abuse", "cloud-vps"],
                "last_reported": "2026-04-03",
                "virustotal_detections": "5/87 engines flagged",
                "first_seen": "2024-02-10",
                "associated_ips": [
                    {"ip": "185.220.101.34", "type": "Tor Exit Node", "country": "DE", "abuse_score": 100},
                    {"ip": "198.44.136.78", "type": "OVH SAS", "country": "FR", "abuse_score": 45},
                ],
                "note": "Part of a rotating proxy pool used across the credential stuffing campaign. Same JA3 fingerprint seen across all source IPs.",
            },
            "device_info": {
                "device_id": "DESKTOP-KJ-0803",
                "type": "desktop",
                "os": "Windows 11 Pro 24H2",
                "last_patch": "2026-03-30",
                "encryption": "BitLocker enabled",
                "edr_status": "CrowdStrike Falcon active — no threats",
                "registered_owner": "kavita.joshi@acmecorp.com",
                "last_scan": "2026-04-04T06:00:00Z",
                "note": "This is the user's legitimate corporate device. The compromised login did NOT originate from this device — it came from an unregistered device/automated client.",
            },
            "email_headers": None,
            "file_analysis": None,
            "network_logs": {
                "connections": [
                    {"timestamp": "2026-04-04T08:02:00Z", "src_ip": "45.33.32.156", "dest_ip": "40.104.36.210", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 2100, "bytes_received": 3800, "duration": "1m", "service": "Exchange Online — Password Change"},
                    {"timestamp": "2026-04-04T08:05:00Z", "src_ip": "45.33.32.156", "dest_ip": "40.104.36.210", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 1500, "bytes_received": 2200, "duration": "30s", "service": "Exchange Online — Mail Forwarding Rule Created"},
                    {"timestamp": "2026-04-04T08:07:00Z", "src_ip": "45.33.32.156", "dest_ip": "login.microsoftonline.com", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 900, "bytes_received": 1100, "duration": "15s", "service": "Azure AD — MFA Device Registration (new authenticator app)"},
                ],
                "summary": "Post-compromise actions within 10 minutes of successful login: (1) password changed, (2) email forwarding rule created to forward all incoming mail to kavita.joshi.backup@protonmail.com, (3) new MFA authenticator device enrolled. All actions from the same Linode IP. Rapid automated post-compromise playbook.",
            },
            "threat_intel": {
                "campaign": "Large-scale credential stuffing campaign — similar to Roku 2024 breach pattern. Uses leaked credential databases and rotating proxy infrastructure to stay below lockout thresholds.",
                "mitre_attack": ["T1110.004 (Credential Stuffing)", "T1114.003 (Email Forwarding Rule)", "T1098.005 (Device Registration)"],
                "related_iocs": ["45.33.32.156", "185.220.101.34", "198.44.136.78", "e7d705a3286e19ea42f587b344ee6865"],
                "threat_actor": "Unknown — financially motivated",
                "confidence": "high",
                "advisory": "Credential stuffing campaign targeting AcmeCorp M365 tenant. Attack uses rotating IPs (Linode, Tor, OVH, residential proxies) with consistent Python httpx JA3 fingerprint. Stays below 5-attempt lockout threshold per account. 99 of 12,408 accounts compromised. Post-compromise playbook: password change, email forwarding to ProtonMail, MFA device enrollment.",
            },
        },
        "ground_truth": {
            "classification": "true_positive",
            "severity": "critical",
            "actions": ["disable_user_account", "reset_user_password", "send_employee_alert", "notify_manager", "escalate_to_tier2"],
            "explanation": "Confirmed credential stuffing compromise. The identical JA3 fingerprint (Python httpx) across all rotating source IPs proves automated tooling. The attack stayed below lockout thresholds (3 fails before success on this account). Post-compromise actions are textbook account takeover: password change to lock out legitimate user, email forwarding to attacker-controlled ProtonMail for data exfiltration, and new MFA device enrollment for persistence. This is one of 99 compromised accounts — must escalate for org-wide incident response. Severity is critical due to HR role with access to employee PII and compensation data.",
        },
        "relevant_investigations": ["login_history", "ip_reputation", "device_info", "network_logs", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # SL-04: Business Travel (Tokyo, approved) -- FP, Medium
    # -----------------------------------------------------------------
    {
        "id": "SL-04",
        "difficulty": "medium",
        "alert": {
            "ticket_id": "INC-2026-04228",
            "timestamp": "2026-04-05T01:20:00Z",
            "source_tool": "Azure Sentinel",
            "alert_type": "suspicious_login",
            "severity_reported": "medium",
            "summary": "First-time login from Japan detected for user anil.bhargava@acmecorp.com. Login from IP 126.115.204.33 (Tokyo, Japan) on registered corporate device. User has no prior login history from Japan.",
            "affected_user": "anil.bhargava@acmecorp.com",
            "affected_device": "LAPTOP-AB-1501",
            "source_ip": "126.115.204.33",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Anil Bhargava",
                "department": "Business Development",
                "role": "Director of Partnerships — APAC",
                "hire_date": "2018-11-05",
                "risk_score": "low",
                "manager": "nandini.rao@acmecorp.com",
                "access_level": "manager",
                "mfa_enabled": True,
                "recent_security_training": "2026-02-15",
                "notes": "Frequent international traveler. Current approved travel: SFO to NRT (Tokyo), April 4-11, 2026. Travel request TR-2026-0389 approved by manager on March 20.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2026-04-05T01:20:00Z", "ip": "126.115.204.33", "location": "Tokyo, Japan", "device": "LAPTOP-AB-1501", "status": "success", "mfa": "passed"},
                    {"timestamp": "2026-04-04T06:00:00Z", "ip": "192.168.10.45", "location": "SFO Airport Lounge WiFi", "device": "LAPTOP-AB-1501", "status": "success", "mfa": "passed"},
                    {"timestamp": "2026-04-03T09:15:00Z", "ip": "10.0.22.67", "location": "Office-Floor6", "device": "LAPTOP-AB-1501", "status": "success", "mfa": "passed"},
                    {"timestamp": "2026-04-02T09:10:00Z", "ip": "10.0.22.67", "location": "Office-Floor6", "device": "LAPTOP-AB-1501", "status": "success", "mfa": "passed"},
                ],
                "summary": "Login progression matches travel itinerary: office on April 2-3, SFO airport on April 4 (departure day), Tokyo on April 5 (arrival). All logins from same registered device with MFA. Flight UA837 SFO->NRT departs 11:30 AM PT on April 4, arrives 3:30 PM JST on April 5 (approx 11 hours).",
            },
            "ip_reputation": {
                "ip": "126.115.204.33",
                "abuse_score": 0,
                "country": "JP",
                "isp": "SoftBank Corp.",
                "asn": "AS17676",
                "threat_tags": [],
                "last_reported": None,
                "virustotal_detections": "0/87 engines flagged",
                "first_seen": "2017-06-12",
                "note": "Residential/hotel broadband ISP in Tokyo, Japan. Clean reputation.",
            },
            "device_info": {
                "device_id": "LAPTOP-AB-1501",
                "type": "laptop",
                "os": "Windows 11 Pro 24H2",
                "last_patch": "2026-04-01",
                "encryption": "BitLocker enabled",
                "edr_status": "CrowdStrike Falcon active — no threats",
                "registered_owner": "anil.bhargava@acmecorp.com",
                "last_scan": "2026-04-05T00:00:00Z",
                "intune_compliant": True,
            },
            "email_headers": None,
            "file_analysis": None,
            "network_logs": {
                "connections": [
                    {"timestamp": "2026-04-05T01:22:00Z", "dest_ip": "13.107.42.11", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 800, "bytes_received": 25000, "duration": "5m", "service": "Outlook Web Access"},
                    {"timestamp": "2026-04-05T01:28:00Z", "dest_ip": "52.114.132.46", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 400, "bytes_received": 15000, "duration": "3m", "service": "Microsoft Teams"},
                ],
                "summary": "Normal business activity: checked email and Teams messages after arriving in Tokyo. No unusual data transfers or suspicious destinations.",
                "travel_verification": {
                    "concur_booking": "TR-2026-0389",
                    "flight": "UA837 SFO→NRT",
                    "departure": "2026-04-04T11:30:00-07:00",
                    "arrival": "2026-04-05T15:30:00+09:00",
                    "hotel": "The Peninsula Tokyo, April 5-11",
                    "approved_by": "nandini.rao@acmecorp.com",
                    "approved_date": "2026-03-20",
                },
            },
            "threat_intel": {
                "campaign": None,
                "mitre_attack": [],
                "related_iocs": [],
                "confidence": "none",
                "advisory": "No threat intelligence matches. Activity is consistent with approved business travel to Tokyo.",
            },
        },
        "ground_truth": {
            "classification": "false_positive",
            "severity": "low",
            "actions": [],
            "explanation": "Legitimate business travel. Login from Tokyo matches approved travel request TR-2026-0389 (flight UA837 SFO->NRT). Login timeline is consistent: SFO airport on April 4 departure day, Tokyo on April 5 arrival day. Same registered Intune-compliant device, MFA passed, clean IP reputation (SoftBank residential/hotel). Normal email and Teams activity post-login. No action required.",
        },
        "relevant_investigations": ["user_profile", "login_history", "ip_reputation", "device_info", "network_logs"],
    },

    # -----------------------------------------------------------------
    # SL-05: Service Account Anomaly (3 AM, no change ticket) -- TP, Medium
    # -----------------------------------------------------------------
    {
        "id": "SL-05",
        "difficulty": "medium",
        "alert": {
            "ticket_id": "INC-2026-04235",
            "timestamp": "2026-04-05T03:14:00Z",
            "source_tool": "Splunk",
            "alert_type": "suspicious_login",
            "severity_reported": "medium",
            "summary": "Service account svc-sqlreport@acmecorp.com logged in from unexpected source 10.40.8.17 (developer workstation) instead of its baseline server 10.40.12.55 (report-server-01). Login occurred at 03:14 AM IST with no associated change ticket. Account accessed sensitive databases not in its normal access pattern.",
            "affected_user": "svc-sqlreport@acmecorp.com",
            "affected_device": "DEV-WS-0817",
            "source_ip": "10.40.8.17",
        },
        "investigation_data": {
            "user_profile": {
                "name": "svc-sqlreport (Service Account)",
                "department": "IT Infrastructure",
                "role": "Automated SQL Reporting Service",
                "hire_date": "N/A — provisioned 2022-08-15",
                "risk_score": "medium",
                "manager": "it-operations@acmecorp.com",
                "access_level": "service_account",
                "mfa_enabled": False,
                "notes": "Service account for automated report generation. Baseline: runs daily at 06:00 AM from report-server-01 (10.40.12.55). Accesses SalesDB and InventoryDB only. Password last rotated 2025-09-01 (overdue by 7 months). No interactive login should ever occur.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2026-04-05T03:14:00Z", "ip": "10.40.8.17", "location": "DEV-WS-0817 (Developer Workstation — Sanjay Gupta)", "device": "DEV-WS-0817", "status": "success", "mfa": "N/A — service account", "login_type": "interactive"},
                    {"timestamp": "2026-04-05T02:00:00Z", "ip": "10.40.12.55", "location": "report-server-01", "device": "report-server-01", "status": "success", "login_type": "batch", "note": "Normal scheduled report run"},
                    {"timestamp": "2026-04-04T06:00:00Z", "ip": "10.40.12.55", "location": "report-server-01", "device": "report-server-01", "status": "success", "login_type": "batch"},
                    {"timestamp": "2026-04-03T06:00:00Z", "ip": "10.40.12.55", "location": "report-server-01", "device": "report-server-01", "status": "success", "login_type": "batch"},
                ],
                "summary": "Service account has a strict baseline: batch logins from report-server-01 at 06:00 AM daily. The 03:14 AM interactive login from developer workstation DEV-WS-0817 is completely anomalous. No change ticket or maintenance window exists for this time.",
            },
            "ip_reputation": {
                "ip": "10.40.8.17",
                "abuse_score": 0,
                "country": "Internal",
                "isp": "AcmeCorp Internal Network — Developer VLAN",
                "threat_tags": [],
                "note": "Internal IP assigned to developer workstation DEV-WS-0817 (Sanjay Gupta, Backend Developer). This workstation is NOT authorized to use the svc-sqlreport service account.",
                "c2_connection_detected": {
                    "dest_ip": "194.26.135.89",
                    "dest_port": 443,
                    "protocol": "HTTPS",
                    "country": "RO",
                    "isp": "M247 Ltd",
                    "asn": "AS9009",
                    "abuse_score": 96,
                    "threat_tags": ["c2-infrastructure", "cobalt-strike", "known-attacker"],
                    "last_reported": "2026-04-04",
                    "note": "Active C2 beacon detected from DEV-WS-0817 to this Romanian IP. Beacon interval: 60 seconds. Associated with Cobalt Strike malleable C2 profile.",
                },
            },
            "device_info": {
                "device_id": "DEV-WS-0817",
                "type": "workstation",
                "os": "Ubuntu 22.04 LTS",
                "last_patch": "2026-03-15",
                "encryption": "LUKS enabled",
                "edr_status": "CrowdStrike Falcon active — WARNING: suspicious process chain detected (node -> /tmp/.cache/update -> beacon)",
                "registered_owner": "sanjay.gupta@acmecorp.com",
                "last_scan": "2026-04-04T18:00:00Z",
                "compromise_indicators": {
                    "trojanized_package": "npm package 'lodash-utils-v2' (typosquat) installed 2026-04-04T14:22:00Z",
                    "persistence": "/tmp/.cache/update — ELF binary, Cobalt Strike beacon",
                    "credential_exposure": "Plaintext credentials for svc-sqlreport found in /home/sanjay.gupta/projects/data-pipeline/.env",
                    "process_tree": "node -> lodash-utils-v2/postinstall.sh -> /tmp/.cache/update -> bash -> sqlcmd",
                },
            },
            "email_headers": None,
            "file_analysis": None,
            "network_logs": {
                "connections": [
                    {"timestamp": "2026-04-04T14:25:00Z", "src_ip": "10.40.8.17", "dest_ip": "194.26.135.89", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 256, "bytes_received": 128, "duration": "ongoing", "note": "C2 beacon — 60-second interval since 14:25 on April 4"},
                    {"timestamp": "2026-04-05T03:15:00Z", "src_ip": "10.40.8.17", "dest_ip": "10.40.5.20", "dest_port": 1433, "protocol": "TDS/SQL", "bytes_sent": 48200, "bytes_received": 2936012800, "duration": "18m", "service": "SQL Server — CustomerPII database"},
                    {"timestamp": "2026-04-05T03:20:00Z", "src_ip": "10.40.8.17", "dest_ip": "10.40.5.20", "dest_port": 1433, "protocol": "TDS/SQL", "bytes_sent": 12400, "bytes_received": 45000000, "duration": "6m", "service": "SQL Server — CreditCardVault database"},
                ],
                "dns_queries": [
                    {"timestamp": "2026-04-05T03:33:00Z", "domain": "cdn-update-service.com", "resolved_ip": "194.26.135.89", "note": "C2 domain — data exfiltration staging"},
                ],
                "summary": "Compromised developer workstation beaconing to C2 since April 4 afternoon. At 03:15 AM, attacker used stolen svc-sqlreport credentials to access SQL Server. 4,211 queries against CustomerPII (2.8 GB) and CreditCardVault (45 MB) databases — neither is in the service account's normal access pattern (only SalesDB and InventoryDB). Total data transferred: ~2.8 GB to workstation, likely staged for exfiltration via C2.",
            },
            "threat_intel": {
                "campaign": "Supply chain compromise via trojanized npm package — developer workstation used as pivot point for database access",
                "mitre_attack": ["T1552.001 (Unsecured Credentials: Credentials In Files)", "T1078.001 (Valid Accounts: Default Accounts)"],
                "related_iocs": ["194.26.135.89", "cdn-update-service.com", "lodash-utils-v2 (npm typosquat)"],
                "threat_actor": "Unknown — likely financially motivated (targeting PII and credit card data)",
                "confidence": "high",
                "advisory": "Supply chain attack via typosquatted npm package compromised developer workstation. Attacker discovered plaintext service account credentials in .env file and pivoted to access sensitive databases. Service account password has not been rotated in 7 months — well outside policy. Immediate containment required.",
            },
        },
        "ground_truth": {
            "classification": "true_positive",
            "severity": "critical",
            "actions": ["disable_user_account", "isolate_device", "send_employee_alert", "escalate_to_tier2"],
            "explanation": "Confirmed compromise chain: (1) developer workstation compromised via trojanized npm package (lodash-utils-v2 typosquat), (2) Cobalt Strike beacon established C2 to 194.26.135.89 (M247 Ltd, Romania, AbuseIPDB 96%), (3) attacker found plaintext svc-sqlreport credentials in .env file, (4) used service account to access CustomerPII (2.8 GB) and CreditCardVault (45 MB) databases at 3 AM — neither database is in the service account's normal scope. Severity is critical: PII and credit card data breach requiring regulatory notification. Disable service account, isolate workstation, escalate immediately.",
        },
        "relevant_investigations": ["user_profile", "login_history", "ip_reputation", "device_info", "network_logs", "threat_intel"],
    },

    # -----------------------------------------------------------------
    # SL-06: New Device Enrollment (new phone, IT ticket) -- FP, Easy
    # -----------------------------------------------------------------
    {
        "id": "SL-06",
        "difficulty": "easy",
        "alert": {
            "ticket_id": "INC-2026-04242",
            "timestamp": "2026-04-05T11:45:00Z",
            "source_tool": "Okta",
            "alert_type": "suspicious_login",
            "severity_reported": "medium",
            "summary": "MFA factor re-enrollment detected for user pooja.menon@acmecorp.com. Old authenticator factor deactivated and new factor enrolled. This may indicate an account takeover attempt via MFA manipulation.",
            "affected_user": "pooja.menon@acmecorp.com",
            "affected_device": "LAPTOP-PM-0912",
            "source_ip": "103.108.207.18",
        },
        "investigation_data": {
            "user_profile": {
                "name": "Pooja Menon",
                "department": "Design",
                "role": "UX Designer",
                "hire_date": "2022-04-18",
                "risk_score": "low",
                "manager": "rahul.deshpande@acmecorp.com",
                "access_level": "standard",
                "mfa_enabled": True,
                "recent_security_training": "2026-03-05",
                "notes": "Submitted IT support ticket INC-2026-041892 on April 4 for new phone setup and MFA re-enrollment. Ticket approved by helpdesk.",
            },
            "login_history": {
                "entries": [
                    {"timestamp": "2026-04-05T11:45:00Z", "ip": "103.108.207.18", "location": "Pune, India", "device": "LAPTOP-PM-0912", "status": "success", "mfa": "new factor enrolled", "okta_event": "user.mfa.factor.activate"},
                    {"timestamp": "2026-04-05T11:40:00Z", "ip": "10.0.25.110", "location": "Office-Floor4 (IT Helpdesk)", "device": "ADMIN-HELPDESK-03", "status": "admin_action", "mfa": "old factor deactivated", "okta_event": "user.mfa.factor.deactivate", "admin_user": "helpdesk.admin@acmecorp.com"},
                    {"timestamp": "2026-04-05T09:10:00Z", "ip": "103.108.207.18", "location": "Pune, India", "device": "LAPTOP-PM-0912", "status": "success", "mfa": "passed"},
                    {"timestamp": "2026-04-04T09:05:00Z", "ip": "103.108.207.18", "location": "Pune, India", "device": "LAPTOP-PM-0912", "status": "success", "mfa": "passed"},
                    {"timestamp": "2026-04-03T09:15:00Z", "ip": "103.108.207.18", "location": "Pune, India", "device": "LAPTOP-PM-0912", "status": "success", "mfa": "passed"},
                ],
                "summary": "Consistent login pattern from Pune, India on the same registered device. MFA factor deactivation was performed by helpdesk admin from the internal IT helpdesk subnet. New factor enrollment occurred 5 minutes later from user's normal IP. IT ticket INC-2026-041892 authorizes this change.",
            },
            "ip_reputation": {
                "ip": "103.108.207.18",
                "abuse_score": 2,
                "country": "IN",
                "isp": "Reliance Jio Infocomm Limited",
                "asn": "AS55836",
                "threat_tags": [],
                "last_reported": None,
                "virustotal_detections": "0/87 engines flagged",
                "first_seen": "2021-08-20",
                "note": "Residential broadband ISP in Pune, India. Clean reputation. This IP has been the user's consistent login source for the past 6 months.",
            },
            "device_info": {
                "device_id": "LAPTOP-PM-0912",
                "type": "laptop",
                "os": "macOS 15.3 Sequoia",
                "last_patch": "2026-04-02",
                "encryption": "FileVault enabled",
                "edr_status": "CrowdStrike Falcon active — no threats",
                "registered_owner": "pooja.menon@acmecorp.com",
                "last_scan": "2026-04-05T06:00:00Z",
                "intune_compliant": True,
            },
            "email_headers": None,
            "file_analysis": None,
            "network_logs": {
                "connections": [
                    {"timestamp": "2026-04-05T11:46:00Z", "dest_ip": "13.107.42.11", "dest_port": 443, "protocol": "HTTPS", "bytes_sent": 500, "bytes_received": 18000, "duration": "3m", "service": "Outlook Web Access"},
                ],
                "summary": "Normal email access after MFA re-enrollment. No unusual data transfers or suspicious connections.",
                "it_ticket_verification": {
                    "ticket_id": "INC-2026-041892",
                    "created": "2026-04-04T14:30:00Z",
                    "created_by": "pooja.menon@acmecorp.com",
                    "category": "Hardware — New Device Setup",
                    "description": "Got new iPhone 16, need to re-enroll Okta Verify MFA. Old phone (iPhone 13) is being traded in.",
                    "assigned_to": "helpdesk.admin@acmecorp.com",
                    "status": "resolved",
                    "resolution": "Old Okta Verify factor deactivated. User enrolled new factor on new iPhone 16 in person at IT helpdesk. Identity verified via employee badge.",
                    "resolved_at": "2026-04-05T11:50:00Z",
                },
            },
            "threat_intel": {
                "campaign": None,
                "mitre_attack": [],
                "related_iocs": [],
                "confidence": "none",
                "advisory": "No threat intelligence matches. MFA re-enrollment is consistent with documented IT support ticket and helpdesk-assisted process.",
            },
        },
        "ground_truth": {
            "classification": "false_positive",
            "severity": "low",
            "actions": [],
            "explanation": "Legitimate MFA re-enrollment for new phone. IT ticket INC-2026-041892 documents the request, created by the user the day before. Helpdesk admin deactivated old factor from internal IT subnet, user enrolled new factor from their consistent home IP in Pune (103.108.207.18, Jio, AbuseIPDB 2%). Same registered Intune-compliant device, identity verified in person via employee badge. No indicators of compromise. No action required.",
        },
        "relevant_investigations": ["user_profile", "login_history", "ip_reputation", "device_info", "network_logs"],
    },
]
